package com.i84.earnpoint.mapper;

import java.util.List;
import java.util.Map;

import com.i84.earnpoint.gdcl.BO.SerchBO;
import com.i84.earnpoint.model.ArchivesPtInfo;

public interface ArchivesPtInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archives_pt_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archives_pt_info
     *
     * @mbggenerated
     */
    int insert(ArchivesPtInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archives_pt_info
     *
     * @mbggenerated
     */
    int insertSelective(ArchivesPtInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archives_pt_info
     *
     * @mbggenerated
     */
    ArchivesPtInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archives_pt_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ArchivesPtInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archives_pt_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ArchivesPtInfo record);
    
    List<Map<String,Object>> selectByPno(ArchivesPtInfo record);

	int sort(SerchBO serchBO);
	
    Map<String,Object> getsort(Map<String,Object> map);
}