package com.i84.earnpoint.mapper;

import java.util.List;
import java.util.Map;

import com.i84.earnpoint.model.PersonStateAllowance;

/**
 * 享受国务院特殊津贴
 * @author Administrator
 *
 */
public interface PersonStateAllowanceMapper {
	/**
	 * 查询人员列表
	 * @param personBasicInfo
	 * @return
	 */
	List<PersonStateAllowance> queryAllowanceList(PersonStateAllowance personStateAllowance);
	int queryAllowanceCnt(PersonStateAllowance personStateAllowance);
	List<PersonStateAllowance> qryAllowanceInfo(Integer pid);
	
	
	void delete(PersonStateAllowance personStateAllowance);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_state_allowance
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_state_allowance
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    int insert(PersonStateAllowance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_state_allowance
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    int insertSelective(PersonStateAllowance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_state_allowance
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    PersonStateAllowance selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_state_allowance
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    int updateByPrimaryKeySelective(PersonStateAllowance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_state_allowance
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    int updateByPrimaryKey(PersonStateAllowance record);
    
    int countTsjtzsList(Map<String, Object> params);
}