package com.i84.earnpoint.mapper;

import com.i84.earnpoint.model.ClassActionInfo;

public interface ClassActionInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_action_info
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_action_info
	 * @mbggenerated
	 */
	int insert(ClassActionInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_action_info
	 * @mbggenerated
	 */
	int insertSelective(ClassActionInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_action_info
	 * @mbggenerated
	 */
	ClassActionInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_action_info
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(ClassActionInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_action_info
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ClassActionInfo record);
}