package com.i84.earnpoint.model;

import java.io.Serializable;
import java.util.Date;

import com.i84.earnpoint.model.Page;

public class PersonBasicInfo extends Page implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_basic_info.id
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_basic_info.org_code
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_basic_info.person_name
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    private String personName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_basic_info.sex
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_basic_info.identity_number
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    private String identityNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_basic_info.ethnic
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    private String ethnic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_basic_info.birthday
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_basic_info.political_status
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    private String politicalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_basic_info.native_place
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    private String nativePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_basic_info.registered_place
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    private String registeredPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_basic_info.telephone
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_basic_info.title
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_basic_info.industry
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    private String industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_basic_info.address
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_basic_info.wechat
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_basic_info.qq
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_basic_info.email
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    private String email;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_basic_info.train_record
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    private String trainRecord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_basic_info.achievement
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    private String achievement;
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_basic_info.status
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_basic_info.uid
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_basic_info.content
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    private String content;
    
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_basic_info.id
     *
     * @return the value of person_basic_info.id
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_basic_info.id
     *
     * @param id the value for person_basic_info.id
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_basic_info.org_code
     *
     * @return the value of person_basic_info.org_code
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_basic_info.org_code
     *
     * @param orgCode the value for person_basic_info.org_code
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_basic_info.person_name
     *
     * @return the value of person_basic_info.person_name
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_basic_info.person_name
     *
     * @param personName the value for person_basic_info.person_name
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public void setPersonName(String personName) {
        this.personName = personName == null ? null : personName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_basic_info.sex
     *
     * @return the value of person_basic_info.sex
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_basic_info.sex
     *
     * @param sex the value for person_basic_info.sex
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_basic_info.identity_number
     *
     * @return the value of person_basic_info.identity_number
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public String getIdentityNumber() {
        return identityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_basic_info.identity_number
     *
     * @param identityNumber the value for person_basic_info.identity_number
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public void setIdentityNumber(String identityNumber) {
        this.identityNumber = identityNumber == null ? null : identityNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_basic_info.ethnic
     *
     * @return the value of person_basic_info.ethnic
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public String getEthnic() {
        return ethnic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_basic_info.ethnic
     *
     * @param ethnic the value for person_basic_info.ethnic
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public void setEthnic(String ethnic) {
        this.ethnic = ethnic == null ? null : ethnic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_basic_info.birthday
     *
     * @return the value of person_basic_info.birthday
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_basic_info.birthday
     *
     * @param birthday the value for person_basic_info.birthday
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_basic_info.political_status
     *
     * @return the value of person_basic_info.political_status
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public String getPoliticalStatus() {
        return politicalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_basic_info.political_status
     *
     * @param politicalStatus the value for person_basic_info.political_status
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public void setPoliticalStatus(String politicalStatus) {
        this.politicalStatus = politicalStatus == null ? null : politicalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_basic_info.native_place
     *
     * @return the value of person_basic_info.native_place
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public String getNativePlace() {
        return nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_basic_info.native_place
     *
     * @param nativePlace the value for person_basic_info.native_place
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace == null ? null : nativePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_basic_info.registered_place
     *
     * @return the value of person_basic_info.registered_place
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public String getRegisteredPlace() {
        return registeredPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_basic_info.registered_place
     *
     * @param registeredPlace the value for person_basic_info.registered_place
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public void setRegisteredPlace(String registeredPlace) {
        this.registeredPlace = registeredPlace == null ? null : registeredPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_basic_info.telephone
     *
     * @return the value of person_basic_info.telephone
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_basic_info.telephone
     *
     * @param telephone the value for person_basic_info.telephone
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_basic_info.title
     *
     * @return the value of person_basic_info.title
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_basic_info.title
     *
     * @param title the value for person_basic_info.title
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_basic_info.industry
     *
     * @return the value of person_basic_info.industry
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_basic_info.industry
     *
     * @param industry the value for person_basic_info.industry
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_basic_info.address
     *
     * @return the value of person_basic_info.address
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_basic_info.address
     *
     * @param address the value for person_basic_info.address
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_basic_info.wechat
     *
     * @return the value of person_basic_info.wechat
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_basic_info.wechat
     *
     * @param wechat the value for person_basic_info.wechat
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_basic_info.qq
     *
     * @return the value of person_basic_info.qq
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_basic_info.qq
     *
     * @param qq the value for person_basic_info.qq
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_basic_info.email
     *
     * @return the value of person_basic_info.email
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_basic_info.email
     *
     * @param email the value for person_basic_info.email
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_basic_info.train_record
     *
     * @return the value of person_basic_info.train_record
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public String getTrainRecord() {
        return trainRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_basic_info.train_record
     *
     * @param trainRecord the value for person_basic_info.train_record
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public void setTrainRecord(String trainRecord) {
        this.trainRecord = trainRecord == null ? null : trainRecord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_basic_info.achievement
     *
     * @return the value of person_basic_info.achievement
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public String getAchievement() {
        return achievement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_basic_info.achievement
     *
     * @param achievement the value for person_basic_info.achievement
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public void setAchievement(String achievement) {
        this.achievement = achievement == null ? null : achievement.trim();
    }
    
    public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_basic_info.status
     *
     * @return the value of person_basic_info.status
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_basic_info.status
     *
     * @param status the value for person_basic_info.status
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_basic_info.uid
     *
     * @return the value of person_basic_info.uid
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_basic_info.uid
     *
     * @param uid the value for person_basic_info.uid
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_basic_info.content
     *
     * @return the value of person_basic_info.content
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_basic_info.content
     *
     * @param content the value for person_basic_info.content
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
    
    
}