package com.i84.earnpoint.model;

import java.util.Date;

public class RewardsInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rewards_info.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rewards_info.uid
	 * @mbggenerated
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rewards_info.reward_name
	 * @mbggenerated
	 */
	private String rewardName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rewards_info.en_name
	 * @mbggenerated
	 */
	private String enName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rewards_info.pz_date
	 * @mbggenerated
	 */
    private String pzDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rewards_info.cx_date
	 * @mbggenerated
	 */
    private String cxDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rewards_info.p_date
	 * @mbggenerated
	 */
    private String pDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rewards_info.p_uid
	 * @mbggenerated
	 */
	private Integer pUid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rewards_info.del_date
	 * @mbggenerated
	 */
	private Date delDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rewards_info.id
	 * @return  the value of rewards_info.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rewards_info.id
	 * @param id  the value for rewards_info.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rewards_info.uid
	 * @return  the value of rewards_info.uid
	 * @mbggenerated
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rewards_info.uid
	 * @param uid  the value for rewards_info.uid
	 * @mbggenerated
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rewards_info.reward_name
	 * @return  the value of rewards_info.reward_name
	 * @mbggenerated
	 */
	public String getRewardName() {
		return rewardName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rewards_info.reward_name
	 * @param rewardName  the value for rewards_info.reward_name
	 * @mbggenerated
	 */
	public void setRewardName(String rewardName) {
		this.rewardName = rewardName == null ? null : rewardName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rewards_info.en_name
	 * @return  the value of rewards_info.en_name
	 * @mbggenerated
	 */
	public String getEnName() {
		return enName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rewards_info.en_name
	 * @param enName  the value for rewards_info.en_name
	 * @mbggenerated
	 */
	public void setEnName(String enName) {
		this.enName = enName == null ? null : enName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rewards_info.pz_date
	 * @return  the value of rewards_info.pz_date
	 * @mbggenerated
	 */
	public String getPzDate() {
		return pzDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rewards_info.pz_date
	 * @param pzDate  the value for rewards_info.pz_date
	 * @mbggenerated
	 */
	public void setPzDate(String pzDate) {
		this.pzDate = pzDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rewards_info.cx_date
	 * @return  the value of rewards_info.cx_date
	 * @mbggenerated
	 */
	public String getCxDate() {
		return cxDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rewards_info.cx_date
	 * @param cxDate  the value for rewards_info.cx_date
	 * @mbggenerated
	 */
	public void setCxDate(String cxDate) {
		this.cxDate = cxDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rewards_info.p_date
	 * @return  the value of rewards_info.p_date
	 * @mbggenerated
	 */
	public String getpDate() {
		return pDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rewards_info.p_date
	 * @param pDate  the value for rewards_info.p_date
	 * @mbggenerated
	 */
	public void setpDate(String pDate) {
		this.pDate = pDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rewards_info.p_uid
	 * @return  the value of rewards_info.p_uid
	 * @mbggenerated
	 */
	public Integer getpUid() {
		if(pUid==null)
			return 0;
		return pUid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rewards_info.p_uid
	 * @param pUid  the value for rewards_info.p_uid
	 * @mbggenerated
	 */
	public void setpUid(Integer pUid) {
		this.pUid = pUid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rewards_info.del_date
	 * @return  the value of rewards_info.del_date
	 * @mbggenerated
	 */
	public Date getDelDate() {
		return delDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rewards_info.del_date
	 * @param delDate  the value for rewards_info.del_date
	 * @mbggenerated
	 */
	public void setDelDate(Date delDate) {
		this.delDate = delDate;
	}
}