package com.i84.earnpoint.model;

import java.util.Date;

public class OfficialInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column official_info.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column official_info.p_level
	 * @mbggenerated
	 */
	private String pLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column official_info.p_method
	 * @mbggenerated
	 */
	private String pMethod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column official_info.pro_z_name
	 * @mbggenerated
	 */
	private String proZName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column official_info.pro_name
	 * @mbggenerated
	 */
	private String proName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column official_info.department_id
	 * @mbggenerated
	 */
	private String departmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column official_info.remark
	 * @mbggenerated
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column official_info.pz_no
	 * @mbggenerated
	 */
	private String pzNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column official_info.pz_date1
	 * @mbggenerated
	 */
	private String pzDate1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column official_info.p_date
	 * @mbggenerated
	 */
	private Date pDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column official_info.p_uid
	 * @mbggenerated
	 */
	private Integer pUid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column official_info.del_date
	 * @mbggenerated
	 */
	private Date delDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column official_info.uid
	 * @mbggenerated
	 */
	private Integer uid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column official_info.id
	 * @return  the value of official_info.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column official_info.id
	 * @param id  the value for official_info.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column official_info.p_level
	 * @return  the value of official_info.p_level
	 * @mbggenerated
	 */
	public String getpLevel() {
		return pLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column official_info.p_level
	 * @param pLevel  the value for official_info.p_level
	 * @mbggenerated
	 */
	public void setpLevel(String pLevel) {
		this.pLevel = pLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column official_info.p_method
	 * @return  the value of official_info.p_method
	 * @mbggenerated
	 */
	public String getpMethod() {
		return pMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column official_info.p_method
	 * @param pMethod  the value for official_info.p_method
	 * @mbggenerated
	 */
	public void setpMethod(String pMethod) {
		this.pMethod = pMethod == null ? null : pMethod.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column official_info.pro_z_name
	 * @return  the value of official_info.pro_z_name
	 * @mbggenerated
	 */
	public String getProZName() {
		return proZName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column official_info.pro_z_name
	 * @param proZName  the value for official_info.pro_z_name
	 * @mbggenerated
	 */
	public void setProZName(String proZName) {
		this.proZName = proZName == null ? null : proZName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column official_info.pro_name
	 * @return  the value of official_info.pro_name
	 * @mbggenerated
	 */
	public String getProName() {
		return proName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column official_info.pro_name
	 * @param proName  the value for official_info.pro_name
	 * @mbggenerated
	 */
	public void setProName(String proName) {
		this.proName = proName == null ? null : proName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column official_info.department_id
	 * @return  the value of official_info.department_id
	 * @mbggenerated
	 */
	public String getDepartmentId() {
		return departmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column official_info.department_id
	 * @param departmentId  the value for official_info.department_id
	 * @mbggenerated
	 */
	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column official_info.remark
	 * @return  the value of official_info.remark
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column official_info.remark
	 * @param remark  the value for official_info.remark
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column official_info.pz_no
	 * @return  the value of official_info.pz_no
	 * @mbggenerated
	 */
	public String getPzNo() {
		return pzNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column official_info.pz_no
	 * @param pzNo  the value for official_info.pz_no
	 * @mbggenerated
	 */
	public void setPzNo(String pzNo) {
		this.pzNo = pzNo == null ? null : pzNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column official_info.pz_date1
	 * @return  the value of official_info.pz_date1
	 * @mbggenerated
	 */
	public String getPzDate1() {
		return pzDate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column official_info.pz_date1
	 * @param pzDate1  the value for official_info.pz_date1
	 * @mbggenerated
	 */
	public void setPzDate1(String pzDate1) {
		this.pzDate1 = pzDate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column official_info.p_date
	 * @return  the value of official_info.p_date
	 * @mbggenerated
	 */
	public Date getpDate() {
		return pDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column official_info.p_date
	 * @param pDate  the value for official_info.p_date
	 * @mbggenerated
	 */
	public void setpDate(Date pDate) {
		this.pDate = pDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column official_info.p_uid
	 * @return  the value of official_info.p_uid
	 * @mbggenerated
	 */
	public Integer getpUid() {
		if(pUid==null)
			return 0;
		return pUid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column official_info.p_uid
	 * @param pUid  the value for official_info.p_uid
	 * @mbggenerated
	 */
	public void setpUid(Integer pUid) {
		this.pUid = pUid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column official_info.del_date
	 * @return  the value of official_info.del_date
	 * @mbggenerated
	 */
	public Date getDelDate() {
		return delDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column official_info.del_date
	 * @param delDate  the value for official_info.del_date
	 * @mbggenerated
	 */
	public void setDelDate(Date delDate) {
		this.delDate = delDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column official_info.uid
	 * @return  the value of official_info.uid
	 * @mbggenerated
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column official_info.uid
	 * @param uid  the value for official_info.uid
	 * @mbggenerated
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}
}