package com.i84.earnpoint.mapper;

import com.i84.earnpoint.model.AqscBmInfo;

public interface AqscBmInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aqsc_bm_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aqsc_bm_info
     *
     * @mbggenerated
     */
    int insert(AqscBmInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aqsc_bm_info
     *
     * @mbggenerated
     */
    int insertSelective(AqscBmInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aqsc_bm_info
     *
     * @mbggenerated
     */
    AqscBmInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aqsc_bm_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AqscBmInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aqsc_bm_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AqscBmInfo record);
}