package com.i84.earnpoint.mapper;

import com.i84.earnpoint.model.BgActivityUserScoreInfo;
import com.i84.earnpoint.model.BgActivityUserScoreInfoExample;
import com.i84.earnpoint.model.ExportScore;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface BgActivityUserScoreInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_score_info
     *
     * @mbg.generated Sun Oct 23 09:08:28 CST 2016
     */
    long countByExample(BgActivityUserScoreInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_score_info
     *
     * @mbg.generated Sun Oct 23 09:08:28 CST 2016
     */
    int deleteByExample(BgActivityUserScoreInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_score_info
     *
     * @mbg.generated Sun Oct 23 09:08:28 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_score_info
     *
     * @mbg.generated Sun Oct 23 09:08:28 CST 2016
     */
    int insert(BgActivityUserScoreInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_score_info
     *
     * @mbg.generated Sun Oct 23 09:08:28 CST 2016
     */
    int insertSelective(BgActivityUserScoreInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_score_info
     *
     * @mbg.generated Sun Oct 23 09:08:28 CST 2016
     */
    List<BgActivityUserScoreInfo> selectByExample(BgActivityUserScoreInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_score_info
     *
     * @mbg.generated Sun Oct 23 09:08:28 CST 2016
     */
    BgActivityUserScoreInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_score_info
     *
     * @mbg.generated Sun Oct 23 09:08:28 CST 2016
     */
    int updateByExampleSelective(@Param("record") BgActivityUserScoreInfo record, @Param("example") BgActivityUserScoreInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_score_info
     *
     * @mbg.generated Sun Oct 23 09:08:28 CST 2016
     */
    int updateByExample(@Param("record") BgActivityUserScoreInfo record, @Param("example") BgActivityUserScoreInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_score_info
     *
     * @mbg.generated Sun Oct 23 09:08:28 CST 2016
     */
    int updateByPrimaryKeySelective(BgActivityUserScoreInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_score_info
     *
     * @mbg.generated Sun Oct 23 09:08:28 CST 2016
     */
    int updateByPrimaryKey(BgActivityUserScoreInfo record);
    
    List<Map<String,Object>> activityPlaceList(Map<String,Object> record);
    
    List<Map<String,Object>> userScoreList(Map<String, Object> param);
    
    List<Map<String,Object>> checkIn(Map<String,Object> record);
    List<Map<String,Object>> checkIn3(Map<String,Object> record);
    List<Map<String,Object>> checkIn2(Map<String,Object> record);
    List<Map<String,Object>> checkIn4(Map<String,Object> record);
    int queryUserId(String pnum);
    int deleteOrder(Integer id);
    
    List<ExportScore> exportOrder(Map<String, Object> params);
}