package com.i84.earnpoint.mapper;

import com.i84.earnpoint.model.BgApplyForRegisterInfo;
import com.i84.earnpoint.model.BgApplyForRegisterInfoExample;
import com.i84.earnpoint.model.UserInfo;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BgApplyForRegisterInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_apply_for_register_info
     *
     * @mbg.generated Mon Sep 12 14:12:12 CST 2016
     */
    long countByExample(BgApplyForRegisterInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_apply_for_register_info
     *
     * @mbg.generated Mon Sep 12 14:12:12 CST 2016
     */
    int deleteByExample(BgApplyForRegisterInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_apply_for_register_info
     *
     * @mbg.generated Mon Sep 12 14:12:12 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_apply_for_register_info
     *
     * @mbg.generated Mon Sep 12 14:12:12 CST 2016
     */
    int insert(BgApplyForRegisterInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_apply_for_register_info
     *
     * @mbg.generated Mon Sep 12 14:12:12 CST 2016
     */
    int insertSelective(BgApplyForRegisterInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_apply_for_register_info
     *
     * @mbg.generated Mon Sep 12 14:12:12 CST 2016
     */
    List<BgApplyForRegisterInfo> selectByExample(BgApplyForRegisterInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_apply_for_register_info
     *
     * @mbg.generated Mon Sep 12 14:12:12 CST 2016
     */
    BgApplyForRegisterInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_apply_for_register_info
     *
     * @mbg.generated Mon Sep 12 14:12:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") BgApplyForRegisterInfo record, @Param("example") BgApplyForRegisterInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_apply_for_register_info
     *
     * @mbg.generated Mon Sep 12 14:12:12 CST 2016
     */
    int updateByExample(@Param("record") BgApplyForRegisterInfo record, @Param("example") BgApplyForRegisterInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_apply_for_register_info
     *
     * @mbg.generated Mon Sep 12 14:12:12 CST 2016
     */
    int updateByPrimaryKeySelective(BgApplyForRegisterInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_apply_for_register_info
     *
     * @mbg.generated Mon Sep 12 14:12:12 CST 2016
     */
    int updateByPrimaryKey(BgApplyForRegisterInfo record);
    
    BgApplyForRegisterInfo queryBgApplyForRegisterInfoByUserId(BgApplyForRegisterInfo bgApplyForRegisterInfo);
    
    UserInfo queryUserInfoByUserId(int id);
}