package com.i84.earnpoint.mapper;

import com.i84.earnpoint.model.BgEnterprisePlaceInfo;
import com.i84.earnpoint.model.BgEnterprisePlaceInfoExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface BgEnterprisePlaceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_enterprise_place_info
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    long countByExample(BgEnterprisePlaceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_enterprise_place_info
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    int deleteByExample(BgEnterprisePlaceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_enterprise_place_info
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_enterprise_place_info
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    int insert(BgEnterprisePlaceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_enterprise_place_info
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    int insertSelective(BgEnterprisePlaceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_enterprise_place_info
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    List<BgEnterprisePlaceInfo> selectByExample(BgEnterprisePlaceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_enterprise_place_info
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    BgEnterprisePlaceInfo selectByPrimaryKey(Integer id);
    Map<String, Object> selectByPrimaryKey2(Integer id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_enterprise_place_info
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    int updateByExampleSelective(@Param("record") BgEnterprisePlaceInfo record, @Param("example") BgEnterprisePlaceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_enterprise_place_info
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    int updateByExample(@Param("record") BgEnterprisePlaceInfo record, @Param("example") BgEnterprisePlaceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_enterprise_place_info
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    int updateByPrimaryKeySelective(BgEnterprisePlaceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_enterprise_place_info
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    int updateByPrimaryKey(BgEnterprisePlaceInfo record);
    int updateByPlaceId(BgEnterprisePlaceInfo record);
    
    
    List<Map<String,Object>> querySelected(Map<String,Object> record);
    
    List<Map<String,Object>> queryUnSelected(Map<String,Object> record);
    
    Map<String,Object> checkActivityBeginTime(Map<String,Object> record);
    BgEnterprisePlaceInfo checkByPlaceId(Integer id);
    
}