package com.i84.earnpoint.mapper;

import java.util.List;
import java.util.Map;

import com.i84.earnpoint.model.PersonEducationInfo;
/**
 * 学习经历
 * @author Administrator
 *
 */
public interface PersonEducationInfoMapper {
	/**
	 * 查询人员列表
	 * @param personBasicInfo
	 * @return
	 */
	List<PersonEducationInfo> queryEducationList(PersonEducationInfo personEducationInfo);
	int queryEducationCnt(PersonEducationInfo personBasicInfo);
	List<PersonEducationInfo> qryEducationInfo(Integer pid);
	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_education_info
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    int deleteByPrimaryKey(Integer id);
    
    void delete(PersonEducationInfo personBasicInfo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_education_info
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    int insert(PersonEducationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_education_info
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    int insertSelective(PersonEducationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_education_info
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    PersonEducationInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_education_info
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    int updateByPrimaryKeySelective(PersonEducationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_education_info
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    int updateByPrimaryKey(PersonEducationInfo record);
    List<Map<String, Object>> countXlList(Map<String, Object> params);
    List<Map<String, Object>> countXwList(Map<String, Object> params);
    int countXwzs(Map<String, Object> params);
    int countXlzs(Map<String, Object> params);
}