package com.i84.earnpoint.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.i84.earnpoint.model.PersonBasicInfo;

public interface PersonBasicInfoMapper {
	/**
	 * 获取人员基本信息列表
	 * @mbggenerated
	 */
	List<Map<String,Object>> selectPersonList(Map<String,Object> record);
	Map<String,Object> qryPersonBasic(Map<String,Object> param);
	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_basic_info
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_basic_info
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    int insert(PersonBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_basic_info
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    int insertSelective(PersonBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_basic_info
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    PersonBasicInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_basic_info
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    int updateByPrimaryKeySelective(PersonBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_basic_info
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(PersonBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_basic_info
     *
     * @mbggenerated Sat Oct 22 15:16:07 CST 2016
     */
    int updateByPrimaryKey(PersonBasicInfo record);
    List<Map<String, Object>> countZrsList(Map<String, Object> record);
    List<Map<String, Object>> countByUnitList(Map<String, Object> record);
    List<Map<String, Object>> degree();
    List<Map<String, Object>> education();
    List<Map<String, Object>> level();
    List<Map<String, Object>> professionalLevel();
    List<Map<String, Object>> rewardsAndPunishments();
    Integer certificateStatistics1();
    Integer certificateStatistics2();
    Integer certificateStatistics3();
    Integer certificateStatistics4();
    Integer certificateStatistics5();
    Integer certificateStatistics6();
    Integer certificateStatistics7();
    List<Map<String,Object>> totalNumber(@Param("year1")String year1,@Param("year2")String year2,@Param("timeType")String timeType);
    List<Map<String,Object>> testLevel(@Param("year1")String year1,@Param("year2")String year2);
    List<Map<String,Object>> unitStatistical();
    List<Map<String,Object>> formsOfLearning(@Param("year1")String year1,@Param("year2")String year2);
    List<Map<String,Object>> school(@Param("year1")String year1,@Param("year2")String year2);
    List<Map<String,Object>> major(@Param("year1")String year1,@Param("year2")String year2);
    List<Map<String,Object>> countman(@Param("year1")String year1,@Param("year2")String year2,@Param("timeType")String timeType);
    List<Map<String,Object>> llr(@Param("year1")String year1,@Param("year2")String year2);





}