package com.i84.earnpoint.mapper;

import java.util.List;
import java.util.Map;

import com.i84.earnpoint.model.ResidenceInfo;

public interface ResidenceInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table residence_info
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table residence_info
	 * @mbggenerated
	 */
	int insert(ResidenceInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table residence_info
	 * @mbggenerated
	 */
	int insertSelective(ResidenceInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table residence_info
	 * @mbggenerated
	 */
	ResidenceInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table residence_info
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(ResidenceInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table residence_info
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ResidenceInfo record);
	/**
	 * 户口信息列表
	 */
	List<Map<String, Object>> queryResidenceIoInfo(Map<String, Object> params);

	ResidenceInfo qryResidenceInfo(Map<String, Object> paramMap);
	
	/**
	 * 户口信息列表
	 * 2017年5月11日11:50:53
	 * 邓祯
	 */
	List<Map<String, Object>> getHkxxList(Map<String, Object> params);
	
	/**
	 * 新增户口信息
	 * @param params
	 * @return
	 */
	int insertSelectivebymap(Map<String,Object> params);

	void insertToResidenceHis(Map<String, Object> his);
	
	Map<String,Object> getresidencebyuid(Integer uid);

	Map<String, Object> GetHkxxInformation(Integer id);

	Map<String, Object> getlatesthkjc(Integer id);

	List<Map<String, Object>> GetHkxxHisInformation(Map<String, Object> params);

	List<Map<String, Object>> GetHkxxHisInformation1(Map<String, Object> params);
}
