package com.i84.earnpoint.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.i84.earnpoint.model.TypeInfo;

public interface TypeInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table type_info
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table type_info
	 * @mbggenerated
	 */
	int insert(TypeInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table type_info
	 * @mbggenerated
	 */
	int insertSelective(TypeInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table type_info
	 * @mbggenerated
	 */
	TypeInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table type_info
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(TypeInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table type_info
	 * @mbggenerated
	 */
	int updateByPrimaryKey(TypeInfo record);

	int insertChild(TypeInfo typeInfo);

	List<TypeInfo> selectListByPrimaryKey(TypeInfo typeInfo);

	List<TypeInfo> selectListByPrimary(TypeInfo typeInfo);

	List<TypeInfo> selectChildListByPrimary(TypeInfo typeInfo);

	int deleteByPrimaryKeys(String[] list);

	List<TypeInfo> findByIds(String[] idArray);
	List<TypeInfo> findByIds2(String[] idArray);
	
	int insertTypeInfo(Map<String,Object>map);
	List<Map<String,Object>>selectYwflList(Map<String,Object>map);
	int updateTypeInfo(Map<String,Object>map); 
	/**
	 * 获取流水号
	 * @return
	 */
	String getNextPno();
	
	List<Map<String,Object>>businessTypeStatistics(@Param("year1")String year1,@Param("year2")String year2);
	List<Map<String,Object>>handle(@Param("year1")String year1,@Param("year2")String year2,@Param("timeType")String timeType);

	
	
	
}