package com.i84.earnpoint.mapper;

import java.util.List;
import java.util.Map;

import com.i84.earnpoint.model.DaExportAllVo;
import com.i84.earnpoint.model.DaExportVo;
import com.i84.earnpoint.model.GzExportVo;
import com.i84.earnpoint.model.UserMgInfo;

public interface UserMgInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_mg_info
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_mg_info
	 * @mbggenerated
	 */
	int insert(UserMgInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_mg_info
	 * @mbggenerated
	 */
	int insertSelective(UserMgInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_mg_info
	 * @mbggenerated
	 */
	UserMgInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_mg_info
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(UserMgInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_mg_info
	 * @mbggenerated
	 */
	int updateByPrimaryKey(UserMgInfo record);

	/**
	 * 审核
	 * @param id
	 */
	void ryxxCheckInfo(Map<String, Object> params);
	
	/**
	 * 获取档案信息列表
	 * @mbggenerated
	 */
	List<Map<String,Object>> selectUserMgInfoList(Map<String,Object> record);
	
	Map<String,Object> selectmaxDpno(Map<String,Object> record);

	
	/**
	 * 统计档案信息
	 * @mbggenerated
	 */
	List<Map<String,Object>> countuUserMgInfoList(Map<String,Object> record);
	
	/**
	 * 导出档案信息
	 * @mbggenerated
	 */
	List<DaExportVo> exportDaList(String[] list);
	List<DaExportAllVo> exportAllDaList();

	List<Map<String, Object>> countuUserMgInfoListBySex(
			Map<String, Object> params);
	/**
	 * 获取下一个档案编号
	 */
	String getNextdPno(Map<String, Object> params);
	
	int updateNextDpno(Map<String, Object> params);
	
	/**
	 * 获取下一个系统编号
	 */
	String getNextPno();
	/**
	 * 系统编号+1
	 */
	int updateNextPno();
	
	void updateIsState(UserMgInfo userMgInfo);

	List<Map<String, Object>> countuUserMgInfoListByBirthday(
			Map<String, Object> params);

	List<Map<String, Object>> countuUserMgInfoListByDegree(
			Map<String, Object> params);

	List<Map<String, Object>> countuUserMgInfoListByZzmm(
			Map<String, Object> params);

	List<Map<String, Object>> countuUserMgInfoListByDtype(
			Map<String, Object> params);

	void updateByUid(UserMgInfo userMgInfo);
	
	Map getdabh(Map<String, Object> params);
	Map getdabh1(Map<String, Object> params);
	
	UserMgInfo selectByUid(Integer id);

	Map<String,Object> getUserMgInfoByPnum(String pnum);
	/**
	 * 通过系统编码获取用户信息
	 * @param pno
	 * @return
	 */
	Map<String,Object> getUserInfoByDpno(String dpno);
}