package com.i84.earnpoint.mapper;

import com.i84.earnpoint.model.ZcCurdissertationInfo;

public interface ZcCurdissertationInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_curdissertation_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_curdissertation_info
     *
     * @mbggenerated
     */
    int insert(ZcCurdissertationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_curdissertation_info
     *
     * @mbggenerated
     */
    int insertSelective(ZcCurdissertationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_curdissertation_info
     *
     * @mbggenerated
     */
    ZcCurdissertationInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_curdissertation_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZcCurdissertationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_curdissertation_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZcCurdissertationInfo record);
}