package com.i84.earnpoint.sydwzp.service;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.i84.earnpoint.model.BgApplyForRegisterInfo;
import com.i84.earnpoint.model.BgApplyForRegisterInfoExample;
import com.i84.earnpoint.model.UserInfo;

public interface BgApplyForRegisterService {

	/**
	 * 根据用户id获取数据
	 * @param bgApplyForRegisterInfo
	 * @return
	 */
	BgApplyForRegisterInfo queryBgApplyForRegisterInfoByUserId(BgApplyForRegisterInfo bgApplyForRegisterInfo);

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_apply_for_register_info
     *
     * @mbggenerated Wed Sep 07 11:34:18 CST 2016
     */
    int countByExample(BgApplyForRegisterInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_apply_for_register_info
     *
     * @mbggenerated Wed Sep 07 11:34:18 CST 2016
     */
    int deleteByExample(BgApplyForRegisterInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_apply_for_register_info
     *
     * @mbggenerated Wed Sep 07 11:34:18 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_apply_for_register_info
     *
     * @mbggenerated Wed Sep 07 11:34:18 CST 2016
     */
    int insert(BgApplyForRegisterInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_apply_for_register_info
     *
     * @mbggenerated Wed Sep 07 11:34:18 CST 2016
     */
    int insertSelective(BgApplyForRegisterInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_apply_for_register_info
     *
     * @mbggenerated Wed Sep 07 11:34:18 CST 2016
     */
    List<BgApplyForRegisterInfo> selectByExample(BgApplyForRegisterInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_apply_for_register_info
     *
     * @mbggenerated Wed Sep 07 11:34:18 CST 2016
     */
    BgApplyForRegisterInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_apply_for_register_info
     *
     * @mbggenerated Wed Sep 07 11:34:18 CST 2016
     */
    int updateByExampleSelective(@Param("record") BgApplyForRegisterInfo record, @Param("example") BgApplyForRegisterInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_apply_for_register_info
     *
     * @mbggenerated Wed Sep 07 11:34:18 CST 2016
     */
    int updateByExample(@Param("record") BgApplyForRegisterInfo record, @Param("example") BgApplyForRegisterInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_apply_for_register_info
     *
     * @mbggenerated Wed Sep 07 11:34:18 CST 2016
     */
    int updateByPrimaryKeySelective(BgApplyForRegisterInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_apply_for_register_info
     *
     * @mbggenerated Wed Sep 07 11:34:18 CST 2016
     */
    int updateByPrimaryKey(BgApplyForRegisterInfo record);
    
    
    UserInfo queryUserInfoByUserId(int id);
}
