package com.i84.earnpoint.mapper;

import java.util.List;

import com.i84.earnpoint.model.DepartmentInfo;

public interface DepartmentInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department_info
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department_info
	 * @mbggenerated
	 */
	int insert(DepartmentInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department_info
	 * @mbggenerated
	 */
	int insertSelective(DepartmentInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department_info
	 * @mbggenerated
	 */
	DepartmentInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department_info
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(DepartmentInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table department_info
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DepartmentInfo record);

	List<DepartmentInfo> selectByPrimaryKeySelective(DepartmentInfo departmentInfo);
	 
	 List<DepartmentInfo> findByIds(String [] idArray);
	
	//int deleteBy
}