package com.i84.earnpoint.model;

import java.util.Date;

public class ExpertActivityInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_activity_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_activity_info.expert_id
     *
     * @mbggenerated
     */
    private Integer expertId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_activity_info.a_id
     *
     * @mbggenerated
     */
    private Integer aId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_activity_info.staff
     *
     * @mbggenerated
     */
    private Integer staff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_activity_info.add_date
     *
     * @mbggenerated
     */
    private Date addDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_activity_info.del_date
     *
     * @mbggenerated
     */
    private Date delDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_activity_info.id
     *
     * @return the value of expert_activity_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_activity_info.id
     *
     * @param id the value for expert_activity_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_activity_info.expert_id
     *
     * @return the value of expert_activity_info.expert_id
     *
     * @mbggenerated
     */
    public Integer getExpertId() {
        return expertId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_activity_info.expert_id
     *
     * @param expertId the value for expert_activity_info.expert_id
     *
     * @mbggenerated
     */
    public void setExpertId(Integer expertId) {
        this.expertId = expertId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_activity_info.a_id
     *
     * @return the value of expert_activity_info.a_id
     *
     * @mbggenerated
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_activity_info.a_id
     *
     * @param aId the value for expert_activity_info.a_id
     *
     * @mbggenerated
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_activity_info.staff
     *
     * @return the value of expert_activity_info.staff
     *
     * @mbggenerated
     */
    public Integer getStaff() {
        return staff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_activity_info.staff
     *
     * @param staff the value for expert_activity_info.staff
     *
     * @mbggenerated
     */
    public void setStaff(Integer staff) {
        this.staff = staff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_activity_info.add_date
     *
     * @return the value of expert_activity_info.add_date
     *
     * @mbggenerated
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_activity_info.add_date
     *
     * @param addDate the value for expert_activity_info.add_date
     *
     * @mbggenerated
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_activity_info.del_date
     *
     * @return the value of expert_activity_info.del_date
     *
     * @mbggenerated
     */
    public Date getDelDate() {
        return delDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_activity_info.del_date
     *
     * @param delDate the value for expert_activity_info.del_date
     *
     * @mbggenerated
     */
    public void setDelDate(Date delDate) {
        this.delDate = delDate;
    }
}