package com.i84.earnpoint.mapper;

import java.util.List;
import java.util.Map;

import com.i84.earnpoint.model.ZcActivityInfo;

public interface ZcActivityInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zc_activity_info
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zc_activity_info
	 * @mbggenerated
	 */
	int insert(ZcActivityInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zc_activity_info
	 * @mbggenerated
	 */
	int insertSelective(ZcActivityInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zc_activity_info
	 * @mbggenerated
	 */
	ZcActivityInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zc_activity_info
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(ZcActivityInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zc_activity_info
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(ZcActivityInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zc_activity_info
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ZcActivityInfo record);

	List<ZcActivityInfo> queryList(ZcActivityInfo record);
	
	Map<String,Object> getAll(ZcActivityInfo record);

	
	
	int getAllCount();
	List<Map<String,Object>> queryBusinessList(Map<String,Object>map);
}