package com.i84.earnpoint.mapper;

import java.util.List;
import java.util.Map;

import com.i84.earnpoint.model.EnterpriseInfo;

public interface EnterpriseInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_info
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_info
	 * @mbggenerated
	 */
	int insert(EnterpriseInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_info
	 * @mbggenerated
	 */
	int insertSelective(EnterpriseInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_info
	 * @mbggenerated
	 */
	EnterpriseInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_info
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(EnterpriseInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_info
	 * @mbggenerated
	 */
     List<Map<String, Object>> enterpriseList(Map<String, Object> map);

	int updateByPrimaryKey(EnterpriseInfo record);

	EnterpriseInfo selectByCcode(EnterpriseInfo record);
	
	EnterpriseInfo selectByPno(EnterpriseInfo record);
	List<EnterpriseInfo> selectBySelective(EnterpriseInfo enterpriseInfo);
	
	List<EnterpriseInfo> selectBySelectiveByCodeOrName(String value);
	
	Map<String, Object> isCode(Map<String, Object> map);
	
    List<Map<String, Object>> selectEnterpriseName(Map<String, Object> map);
   
    List countqysltj(Map map);
    
}