package com.i84.earnpoint.mapper;

import com.i84.earnpoint.model.BgActivityUserPayInfo;
import com.i84.earnpoint.model.BgActivityUserPayInfoExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface BgActivityUserPayInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_pay_info
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    long countByExample(BgActivityUserPayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_pay_info
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    int deleteByExample(BgActivityUserPayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_pay_info
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_pay_info
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    int insert(BgActivityUserPayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_pay_info
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    int insertSelective(BgActivityUserPayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_pay_info
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    List<BgActivityUserPayInfo> selectByExample(BgActivityUserPayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_pay_info
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    BgActivityUserPayInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_pay_info
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    int updateByExampleSelective(@Param("record") BgActivityUserPayInfo record, @Param("example") BgActivityUserPayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_pay_info
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    int updateByExample(@Param("record") BgActivityUserPayInfo record, @Param("example") BgActivityUserPayInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_pay_info
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    int updateByPrimaryKeySelective(BgActivityUserPayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_pay_info
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    int updateByPrimaryKey(BgActivityUserPayInfo record);
    
    BgActivityUserPayInfo getActivityPayInfo(String orderid);
    
    List<Map<String,Object>> userPayList(Map<String, Object> param);
    
    void test1();
    void test2();
}