package com.i84.earnpoint.mapper;

import java.util.List;
import java.util.Map;

import com.i84.earnpoint.model.StudyCurInfo;
import com.i84.earnpoint.model.StudyInfo;

public interface StudyCurInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_cur_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_cur_info
     *
     * @mbggenerated
     */
    int insert(StudyCurInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_cur_info
     *
     * @mbggenerated
     */
    int insertSelective(StudyCurInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_cur_info
     *
     * @mbggenerated
     */
    StudyCurInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_cur_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StudyCurInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_cur_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StudyCurInfo record);
    
    
    List<StudyCurInfo> getInfo(StudyCurInfo record);
}