package com.i84.earnpoint.model;

import java.util.Date;

public class UserPartyInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.uid
	 * @mbggenerated
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.pno
	 * @mbggenerated
	 */
	private String pno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.is_state
	 * @mbggenerated
	 */
	private String isState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.company
	 * @mbggenerated
	 */
	private String company;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.is_in
	 * @mbggenerated
	 */
	private String isIn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.in_date
	 * @mbggenerated
	 */
	private Date inDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.out_date
	 * @mbggenerated
	 */
	private Date outDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.party_date
	 * @mbggenerated
	 */
	private Date partyDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.m_his
	 * @mbggenerated
	 */
	private Float mHis;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.his_date
	 * @mbggenerated
	 */
	private Date hisDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.add_m
	 * @mbggenerated
	 */
	private Float addM;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.need_m
	 * @mbggenerated
	 */
	private Float needM;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.m
	 * @mbggenerated
	 */
	private Float m;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.full_date
	 * @mbggenerated
	 */
	private Date fullDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.j_name1
	 * @mbggenerated
	 */
	private String jName1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.j_name2
	 * @mbggenerated
	 */
	private String jName2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.sq_status
	 * @mbggenerated
	 */
	private String sqStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.rd_status
	 * @mbggenerated
	 */
	private String rdStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.zz_mtr
	 * @mbggenerated
	 */
	private String zzMtr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.py_mtr
	 * @mbggenerated
	 */
	private String pyMtr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.full_rq
	 * @mbggenerated
	 */
	private String fullRq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.remark
	 * @mbggenerated
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.er_msg
	 * @mbggenerated
	 */
	private String erMsg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.del_date
	 * @mbggenerated
	 */
	private Date delDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_party_info.jf_date
	 * @mbggenerated
	 */
	private Date jfDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.id
	 * @return  the value of user_party_info.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.id
	 * @param id  the value for user_party_info.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.uid
	 * @return  the value of user_party_info.uid
	 * @mbggenerated
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.uid
	 * @param uid  the value for user_party_info.uid
	 * @mbggenerated
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.pno
	 * @return  the value of user_party_info.pno
	 * @mbggenerated
	 */
	public String getPno() {
		return pno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.pno
	 * @param pno  the value for user_party_info.pno
	 * @mbggenerated
	 */
	public void setPno(String pno) {
		this.pno = pno == null ? null : pno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.is_state
	 * @return  the value of user_party_info.is_state
	 * @mbggenerated
	 */
	public String getIsState() {
		return isState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.is_state
	 * @param isState  the value for user_party_info.is_state
	 * @mbggenerated
	 */
	public void setIsState(String isState) {
		this.isState = isState == null ? null : isState.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.company
	 * @return  the value of user_party_info.company
	 * @mbggenerated
	 */
	public String getCompany() {
		return company;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.company
	 * @param company  the value for user_party_info.company
	 * @mbggenerated
	 */
	public void setCompany(String company) {
		this.company = company == null ? null : company.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.is_in
	 * @return  the value of user_party_info.is_in
	 * @mbggenerated
	 */
	public String getIsIn() {
		return isIn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.is_in
	 * @param isIn  the value for user_party_info.is_in
	 * @mbggenerated
	 */
	public void setIsIn(String isIn) {
		if(isIn==null||"".equals(isIn))
			this.isIn="1";
		else
			this.isIn = isIn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.in_date
	 * @return  the value of user_party_info.in_date
	 * @mbggenerated
	 */
	public Date getInDate() {
		return inDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.in_date
	 * @param inDate  the value for user_party_info.in_date
	 * @mbggenerated
	 */
	public void setInDate(Date inDate) {
		this.inDate = inDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.out_date
	 * @return  the value of user_party_info.out_date
	 * @mbggenerated
	 */
	public Date getOutDate() {
		return outDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.out_date
	 * @param outDate  the value for user_party_info.out_date
	 * @mbggenerated
	 */
	public void setOutDate(Date outDate) {
		this.outDate = outDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.party_date
	 * @return  the value of user_party_info.party_date
	 * @mbggenerated
	 */
	public Date getPartyDate() {
		return partyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.party_date
	 * @param partyDate  the value for user_party_info.party_date
	 * @mbggenerated
	 */
	public void setPartyDate(Date partyDate) {
		this.partyDate = partyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.m_his
	 * @return  the value of user_party_info.m_his
	 * @mbggenerated
	 */
	public Float getmHis() {
		return mHis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.m_his
	 * @param mHis  the value for user_party_info.m_his
	 * @mbggenerated
	 */
	public void setmHis(Float mHis) {
		this.mHis = mHis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.his_date
	 * @return  the value of user_party_info.his_date
	 * @mbggenerated
	 */
	public Date getHisDate() {
		return hisDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.his_date
	 * @param hisDate  the value for user_party_info.his_date
	 * @mbggenerated
	 */
	public void setHisDate(Date hisDate) {
		this.hisDate = hisDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.add_m
	 * @return  the value of user_party_info.add_m
	 * @mbggenerated
	 */
	public Float getAddM() {
		return addM;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.add_m
	 * @param addM  the value for user_party_info.add_m
	 * @mbggenerated
	 */
	public void setAddM(Float addM) {
		this.addM = addM;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.need_m
	 * @return  the value of user_party_info.need_m
	 * @mbggenerated
	 */
	public Float getNeedM() {
		return needM;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.need_m
	 * @param needM  the value for user_party_info.need_m
	 * @mbggenerated
	 */
	public void setNeedM(Float needM) {
		this.needM = needM;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.m
	 * @return  the value of user_party_info.m
	 * @mbggenerated
	 */
	public Float getM() {
		return m;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.m
	 * @param m  the value for user_party_info.m
	 * @mbggenerated
	 */
	public void setM(Float m) {
		this.m = m;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.full_date
	 * @return  the value of user_party_info.full_date
	 * @mbggenerated
	 */
	public Date getFullDate() {
		return fullDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.full_date
	 * @param fullDate  the value for user_party_info.full_date
	 * @mbggenerated
	 */
	public void setFullDate(Date fullDate) {
		this.fullDate = fullDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.j_name1
	 * @return  the value of user_party_info.j_name1
	 * @mbggenerated
	 */
	public String getjName1() {
		return jName1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.j_name1
	 * @param jName1  the value for user_party_info.j_name1
	 * @mbggenerated
	 */
	public void setjName1(String jName1) {
		this.jName1 = jName1 == null ? null : jName1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.j_name2
	 * @return  the value of user_party_info.j_name2
	 * @mbggenerated
	 */
	public String getjName2() {
		return jName2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.j_name2
	 * @param jName2  the value for user_party_info.j_name2
	 * @mbggenerated
	 */
	public void setjName2(String jName2) {
		this.jName2 = jName2 == null ? null : jName2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.sq_status
	 * @return  the value of user_party_info.sq_status
	 * @mbggenerated
	 */
	public String getSqStatus() {
		return sqStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.sq_status
	 * @param sqStatus  the value for user_party_info.sq_status
	 * @mbggenerated
	 */
	public void setSqStatus(String sqStatus) {
		this.sqStatus = sqStatus == null ? null : sqStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.rd_status
	 * @return  the value of user_party_info.rd_status
	 * @mbggenerated
	 */
	public String getRdStatus() {
		return rdStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.rd_status
	 * @param rdStatus  the value for user_party_info.rd_status
	 * @mbggenerated
	 */
	public void setRdStatus(String rdStatus) {
		this.rdStatus = rdStatus == null ? null : rdStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.zz_mtr
	 * @return  the value of user_party_info.zz_mtr
	 * @mbggenerated
	 */
	public String getZzMtr() {
		return zzMtr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.zz_mtr
	 * @param zzMtr  the value for user_party_info.zz_mtr
	 * @mbggenerated
	 */
	public void setZzMtr(String zzMtr) {
		this.zzMtr = zzMtr == null ? null : zzMtr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.py_mtr
	 * @return  the value of user_party_info.py_mtr
	 * @mbggenerated
	 */
	public String getPyMtr() {
		return pyMtr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.py_mtr
	 * @param pyMtr  the value for user_party_info.py_mtr
	 * @mbggenerated
	 */
	public void setPyMtr(String pyMtr) {
		this.pyMtr = pyMtr == null ? null : pyMtr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.full_rq
	 * @return  the value of user_party_info.full_rq
	 * @mbggenerated
	 */
	public String getFullRq() {
		return fullRq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.full_rq
	 * @param fullRq  the value for user_party_info.full_rq
	 * @mbggenerated
	 */
	public void setFullRq(String fullRq) {
		this.fullRq = fullRq == null ? null : fullRq.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.remark
	 * @return  the value of user_party_info.remark
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.remark
	 * @param remark  the value for user_party_info.remark
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.er_msg
	 * @return  the value of user_party_info.er_msg
	 * @mbggenerated
	 */
	public String getErMsg() {
		return erMsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.er_msg
	 * @param erMsg  the value for user_party_info.er_msg
	 * @mbggenerated
	 */
	public void setErMsg(String erMsg) {
		this.erMsg = erMsg == null ? null : erMsg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.del_date
	 * @return  the value of user_party_info.del_date
	 * @mbggenerated
	 */
	public Date getDelDate() {
		return delDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.del_date
	 * @param delDate  the value for user_party_info.del_date
	 * @mbggenerated
	 */
	public void setDelDate(Date delDate) {
		this.delDate = delDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_party_info.jf_date
	 * @return  the value of user_party_info.jf_date
	 * @mbggenerated
	 */
	public Date getJfDate() {
		return jfDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_party_info.jf_date
	 * @param jfDate  the value for user_party_info.jf_date
	 * @mbggenerated
	 */
	public void setJfDate(Date jfDate) {
		this.jfDate = jfDate;
	}
}