package com.i84.earnpoint.mapper;

import com.i84.earnpoint.model.UserExaminationInfo;

public interface UserExaminationInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_examination_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_examination_info
     *
     * @mbggenerated
     */
    int insert(UserExaminationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_examination_info
     *
     * @mbggenerated
     */
    int insertSelective(UserExaminationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_examination_info
     *
     * @mbggenerated
     */
    UserExaminationInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_examination_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserExaminationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_examination_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserExaminationInfo record);
}