package com.i84.earnpoint.mapper;

import java.util.List;
import java.util.Map;

import com.i84.earnpoint.gdcl.BO.SerchBO;
import com.i84.earnpoint.model.ArchivesDisciplinedInfo;

public interface ArchivesDisciplinedInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archives_disciplined_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archives_disciplined_info
     *
     * @mbggenerated
     */
    int insert(ArchivesDisciplinedInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archives_disciplined_info
     *
     * @mbggenerated
     */
    int insertSelective(ArchivesDisciplinedInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archives_disciplined_info
     *
     * @mbggenerated
     */
    ArchivesDisciplinedInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archives_disciplined_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ArchivesDisciplinedInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archives_disciplined_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ArchivesDisciplinedInfo record);
    
    List<Map<String,Object>> selectByPno(ArchivesDisciplinedInfo record);

	int sort(SerchBO serchBO);
	
    Map<String,Object> getsort(Map<String,Object> map);
}