package com.i84.earnpoint.model;

import java.util.Date;

public class UserBgMoneyInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_bg_money_info.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_bg_money_info.uid
	 * @mbggenerated
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_bg_money_info.paydate
	 * @mbggenerated
	 */
	private Date paydate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_bg_money_info.order_no
	 * @mbggenerated
	 */
	private String orderNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_bg_money_info.order_pno
	 * @mbggenerated
	 */
	private String orderPno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_bg_money_info.pay_state
	 * @mbggenerated
	 */
	private String payState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_bg_money_info.bg_enterprise_id
	 * @mbggenerated
	 */
	private Integer bgEnterpriseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_bg_money_info.bg_department_id
	 * @mbggenerated
	 */
	private Integer bgDepartmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_bg_money_info.is_start
	 * @mbggenerated
	 */
	private String isStart;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_bg_money_info.id
	 * @return  the value of user_bg_money_info.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_bg_money_info.id
	 * @param id  the value for user_bg_money_info.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_bg_money_info.uid
	 * @return  the value of user_bg_money_info.uid
	 * @mbggenerated
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_bg_money_info.uid
	 * @param uid  the value for user_bg_money_info.uid
	 * @mbggenerated
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_bg_money_info.paydate
	 * @return  the value of user_bg_money_info.paydate
	 * @mbggenerated
	 */
	public Date getPaydate() {
		return paydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_bg_money_info.paydate
	 * @param paydate  the value for user_bg_money_info.paydate
	 * @mbggenerated
	 */
	public void setPaydate(Date paydate) {
		this.paydate = paydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_bg_money_info.order_no
	 * @return  the value of user_bg_money_info.order_no
	 * @mbggenerated
	 */
	public String getOrderNo() {
		return orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_bg_money_info.order_no
	 * @param orderNo  the value for user_bg_money_info.order_no
	 * @mbggenerated
	 */
	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo == null ? null : orderNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_bg_money_info.order_pno
	 * @return  the value of user_bg_money_info.order_pno
	 * @mbggenerated
	 */
	public String getOrderPno() {
		return orderPno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_bg_money_info.order_pno
	 * @param orderPno  the value for user_bg_money_info.order_pno
	 * @mbggenerated
	 */
	public void setOrderPno(String orderPno) {
		this.orderPno = orderPno == null ? null : orderPno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_bg_money_info.pay_state
	 * @return  the value of user_bg_money_info.pay_state
	 * @mbggenerated
	 */
	public String getPayState() {
		return payState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_bg_money_info.pay_state
	 * @param payState  the value for user_bg_money_info.pay_state
	 * @mbggenerated
	 */
	public void setPayState(String payState) {
		this.payState = payState == null ? null : payState.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_bg_money_info.bg_enterprise_id
	 * @return  the value of user_bg_money_info.bg_enterprise_id
	 * @mbggenerated
	 */
	public Integer getBgEnterpriseId() {
		return bgEnterpriseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_bg_money_info.bg_enterprise_id
	 * @param bgEnterpriseId  the value for user_bg_money_info.bg_enterprise_id
	 * @mbggenerated
	 */
	public void setBgEnterpriseId(Integer bgEnterpriseId) {
		this.bgEnterpriseId = bgEnterpriseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_bg_money_info.bg_department_id
	 * @return  the value of user_bg_money_info.bg_department_id
	 * @mbggenerated
	 */
	public Integer getBgDepartmentId() {
		return bgDepartmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_bg_money_info.bg_department_id
	 * @param bgDepartmentId  the value for user_bg_money_info.bg_department_id
	 * @mbggenerated
	 */
	public void setBgDepartmentId(Integer bgDepartmentId) {
		this.bgDepartmentId = bgDepartmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_bg_money_info.is_start
	 * @return  the value of user_bg_money_info.is_start
	 * @mbggenerated
	 */
	public String getIsStart() {
		return isStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_bg_money_info.is_start
	 * @param isStart  the value for user_bg_money_info.is_start
	 * @mbggenerated
	 */
	public void setIsStart(String isStart) {
		this.isStart = isStart == null ? null : isStart.trim();
	}
}