package com.i84.earnpoint.mapper;

import java.util.List;
import java.util.Map;

import net.sf.json.JSONArray;

import com.i84.earnpoint.gdcl.BO.SerchBO;
import com.i84.earnpoint.model.ArchivesMyInfo;

public interface ArchivesMyInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archives_my_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archives_my_info
     *
     * @mbggenerated
     */
    int insert(ArchivesMyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archives_my_info
     *
     * @mbggenerated
     */
    int insertSelective(ArchivesMyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archives_my_info
     *
     * @mbggenerated
     */
    ArchivesMyInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archives_my_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ArchivesMyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archives_my_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ArchivesMyInfo record);
    
    List<Map<String,Object>> selectByPno(ArchivesMyInfo record);

	int sort(SerchBO serchBO);

	Map<String, Object> getsort(Map<String, Object> map);
}