package com.i84.earnpoint.model;

import java.util.Date;

public class BgActivityUserPayInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_activity_user_pay_info.id
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_activity_user_pay_info.order_id
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_activity_user_pay_info.p_date
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    private Date pDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_activity_user_pay_info.order_no
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_activity_user_pay_info.m
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    private Float m;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_activity_user_pay_info.state
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_activity_user_pay_info.msg_from_id
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    private String msgFromId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_activity_user_pay_info.remark
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_activity_user_pay_info.uid
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_activity_user_pay_info.item_type
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    private String itemType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_activity_user_pay_info.id
     *
     * @return the value of bg_activity_user_pay_info.id
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_activity_user_pay_info.id
     *
     * @param id the value for bg_activity_user_pay_info.id
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_activity_user_pay_info.order_id
     *
     * @return the value of bg_activity_user_pay_info.order_id
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_activity_user_pay_info.order_id
     *
     * @param orderId the value for bg_activity_user_pay_info.order_id
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_activity_user_pay_info.p_date
     *
     * @return the value of bg_activity_user_pay_info.p_date
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    public Date getpDate() {
        return pDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_activity_user_pay_info.p_date
     *
     * @param pDate the value for bg_activity_user_pay_info.p_date
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    public void setpDate(Date pDate) {
        this.pDate = pDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_activity_user_pay_info.order_no
     *
     * @return the value of bg_activity_user_pay_info.order_no
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_activity_user_pay_info.order_no
     *
     * @param orderNo the value for bg_activity_user_pay_info.order_no
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_activity_user_pay_info.m
     *
     * @return the value of bg_activity_user_pay_info.m
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    public Float getM() {
        return m;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_activity_user_pay_info.m
     *
     * @param m the value for bg_activity_user_pay_info.m
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    public void setM(Float m) {
        this.m = m;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_activity_user_pay_info.state
     *
     * @return the value of bg_activity_user_pay_info.state
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_activity_user_pay_info.state
     *
     * @param state the value for bg_activity_user_pay_info.state
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_activity_user_pay_info.msg_from_id
     *
     * @return the value of bg_activity_user_pay_info.msg_from_id
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    public String getMsgFromId() {
        return msgFromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_activity_user_pay_info.msg_from_id
     *
     * @param msgFromId the value for bg_activity_user_pay_info.msg_from_id
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    public void setMsgFromId(String msgFromId) {
        this.msgFromId = msgFromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_activity_user_pay_info.remark
     *
     * @return the value of bg_activity_user_pay_info.remark
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_activity_user_pay_info.remark
     *
     * @param remark the value for bg_activity_user_pay_info.remark
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_activity_user_pay_info.uid
     *
     * @return the value of bg_activity_user_pay_info.uid
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_activity_user_pay_info.uid
     *
     * @param uid the value for bg_activity_user_pay_info.uid
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_activity_user_pay_info.item_type
     *
     * @return the value of bg_activity_user_pay_info.item_type
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    public String getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_activity_user_pay_info.item_type
     *
     * @param itemType the value for bg_activity_user_pay_info.item_type
     *
     * @mbg.generated Mon Oct 24 21:20:14 CST 2016
     */
    public void setItemType(String itemType) {
        this.itemType = itemType;
    }
}