package com.i84.earnpoint.model;

public class AqscZjmgInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aqsc_zjmg_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aqsc_zjmg_info.enterprise_id
     *
     * @mbggenerated
     */
    private Integer enterpriseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aqsc_zjmg_info.e_type
     *
     * @mbggenerated
     */
    private Integer eType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aqsc_zjmg_info.e_logo
     *
     * @mbggenerated
     */
    private String eLogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aqsc_zjmg_info.e_url
     *
     * @mbggenerated
     */
    private String eUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aqsc_zjmg_info.id
     *
     * @return the value of aqsc_zjmg_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aqsc_zjmg_info.id
     *
     * @param id the value for aqsc_zjmg_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aqsc_zjmg_info.enterprise_id
     *
     * @return the value of aqsc_zjmg_info.enterprise_id
     *
     * @mbggenerated
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aqsc_zjmg_info.enterprise_id
     *
     * @param enterpriseId the value for aqsc_zjmg_info.enterprise_id
     *
     * @mbggenerated
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aqsc_zjmg_info.e_type
     *
     * @return the value of aqsc_zjmg_info.e_type
     *
     * @mbggenerated
     */
    public Integer geteType() {
        return eType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aqsc_zjmg_info.e_type
     *
     * @param eType the value for aqsc_zjmg_info.e_type
     *
     * @mbggenerated
     */
    public void seteType(Integer eType) {
        this.eType = eType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aqsc_zjmg_info.e_logo
     *
     * @return the value of aqsc_zjmg_info.e_logo
     *
     * @mbggenerated
     */
    public String geteLogo() {
        return eLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aqsc_zjmg_info.e_logo
     *
     * @param eLogo the value for aqsc_zjmg_info.e_logo
     *
     * @mbggenerated
     */
    public void seteLogo(String eLogo) {
        this.eLogo = eLogo == null ? null : eLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aqsc_zjmg_info.e_url
     *
     * @return the value of aqsc_zjmg_info.e_url
     *
     * @mbggenerated
     */
    public String geteUrl() {
        return eUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aqsc_zjmg_info.e_url
     *
     * @param eUrl the value for aqsc_zjmg_info.e_url
     *
     * @mbggenerated
     */
    public void seteUrl(String eUrl) {
        this.eUrl = eUrl == null ? null : eUrl.trim();
    }
}