package com.i84.earnpoint.model;

public class BgEnterprisePlace {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_enterprise_place.id
     *
     * @mbggenerated Wed Aug 31 00:43:21 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_enterprise_place.enterprise_id
     *
     * @mbggenerated Wed Aug 31 00:43:21 CST 2016
     */
    private Integer enterpriseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_enterprise_place.place_id
     *
     * @mbggenerated Wed Aug 31 00:43:21 CST 2016
     */
    private Integer placeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_enterprise_place.id
     *
     * @return the value of bg_enterprise_place.id
     *
     * @mbggenerated Wed Aug 31 00:43:21 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_enterprise_place.id
     *
     * @param id the value for bg_enterprise_place.id
     *
     * @mbggenerated Wed Aug 31 00:43:21 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_enterprise_place.enterprise_id
     *
     * @return the value of bg_enterprise_place.enterprise_id
     *
     * @mbggenerated Wed Aug 31 00:43:21 CST 2016
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_enterprise_place.enterprise_id
     *
     * @param enterpriseId the value for bg_enterprise_place.enterprise_id
     *
     * @mbggenerated Wed Aug 31 00:43:21 CST 2016
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_enterprise_place.place_id
     *
     * @return the value of bg_enterprise_place.place_id
     *
     * @mbggenerated Wed Aug 31 00:43:21 CST 2016
     */
    public Integer getPlaceId() {
        return placeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_enterprise_place.place_id
     *
     * @param placeId the value for bg_enterprise_place.place_id
     *
     * @mbggenerated Wed Aug 31 00:43:21 CST 2016
     */
    public void setPlaceId(Integer placeId) {
        this.placeId = placeId;
    }
}