package com.i84.earnpoint.model;

import java.util.Date;

public class EnterpriseInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.pno
	 * @mbggenerated
	 */
	private String pno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.c_code
	 * @mbggenerated
	 */
	private String cCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.pro_id
	 * @mbggenerated
	 */
	private Integer proId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.is_valid
	 * @mbggenerated
	 */
	private String isValid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.is_state
	 * @mbggenerated
	 */
	private Integer isState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.msg_from_id
	 * @mbggenerated
	 */
	private Integer msgFromId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.user_id
	 * @mbggenerated
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.add_date
	 * @mbggenerated
	 */
	private Date addDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.parent_id
	 * @mbggenerated
	 */
	private Integer parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.is_order
	 * @mbggenerated
	 */
	private Integer isOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.sname
	 * @mbggenerated
	 */
	private String sname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.s_area
	 * @mbggenerated
	 */
	private String sArea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.t_type
	 * @mbggenerated
	 */
	private String tType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.slevel
	 * @mbggenerated
	 */
	private Integer slevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.jg_type
	 * @mbggenerated
	 */
	private String jgType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.jj_type
	 * @mbggenerated
	 */
	private String jjType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.area
	 * @mbggenerated
	 */
	private String area;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.tel
	 * @mbggenerated
	 */
	private String tel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.email
	 * @mbggenerated
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.up_date
	 * @mbggenerated
	 */
	private Date upDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.up_type
	 * @mbggenerated
	 */
	private String upType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.up_code
	 * @mbggenerated
	 */
	private String upCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.up_name
	 * @mbggenerated
	 */
	private String upName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.up_uid
	 * @mbggenerated
	 */
	private String upUid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.up_tel
	 * @mbggenerated
	 */
	private String upTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.mg_type
	 * @mbggenerated
	 */
	private String mgType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.uid
	 * @mbggenerated
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.s_msg
	 * @mbggenerated
	 */
	private String sMsg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.del_date
	 * @mbggenerated
	 */
	private Date delDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.pwd
	 * @mbggenerated
	 */
	private String pwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_info.is_authorize
	 * @mbggenerated
	 */
	private int isAuthorize;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.id
	 * @return  the value of enterprise_info.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.id
	 * @param id  the value for enterprise_info.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.pno
	 * @return  the value of enterprise_info.pno
	 * @mbggenerated
	 */
	public String getPno() {
		return pno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.pno
	 * @param pno  the value for enterprise_info.pno
	 * @mbggenerated
	 */
	public void setPno(String pno) {
		this.pno = pno == null ? null : pno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.c_code
	 * @return  the value of enterprise_info.c_code
	 * @mbggenerated
	 */
	public String getcCode() {
		return cCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.c_code
	 * @param cCode  the value for enterprise_info.c_code
	 * @mbggenerated
	 */
	public void setcCode(String cCode) {
		this.cCode = cCode == null ? null : cCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.pro_id
	 * @return  the value of enterprise_info.pro_id
	 * @mbggenerated
	 */
	public Integer getProId() {
		return proId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.pro_id
	 * @param proId  the value for enterprise_info.pro_id
	 * @mbggenerated
	 */
	public void setProId(Integer proId) {
		this.proId = proId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.name
	 * @return  the value of enterprise_info.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.name
	 * @param name  the value for enterprise_info.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.is_valid
	 * @return  the value of enterprise_info.is_valid
	 * @mbggenerated
	 */
	public String getIsValid() {
		return isValid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.is_valid
	 * @param isValid  the value for enterprise_info.is_valid
	 * @mbggenerated
	 */
	public void setIsValid(String isValid) {
		this.isValid = isValid == null ? null : isValid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.is_state
	 * @return  the value of enterprise_info.is_state
	 * @mbggenerated
	 */
	public Integer getIsState() {
		return isState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.is_state
	 * @param isState  the value for enterprise_info.is_state
	 * @mbggenerated
	 */
	public void setIsState(Integer isState) {
		this.isState = isState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.msg_from_id
	 * @return  the value of enterprise_info.msg_from_id
	 * @mbggenerated
	 */
	public Integer getMsgFromId() {
		return msgFromId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.msg_from_id
	 * @param msgFromId  the value for enterprise_info.msg_from_id
	 * @mbggenerated
	 */
	public void setMsgFromId(Integer msgFromId) {
		this.msgFromId = msgFromId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.user_id
	 * @return  the value of enterprise_info.user_id
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.user_id
	 * @param userId  the value for enterprise_info.user_id
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.add_date
	 * @return  the value of enterprise_info.add_date
	 * @mbggenerated
	 */
	public Date getAddDate() {
		return addDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.add_date
	 * @param addDate  the value for enterprise_info.add_date
	 * @mbggenerated
	 */
	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.parent_id
	 * @return  the value of enterprise_info.parent_id
	 * @mbggenerated
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.parent_id
	 * @param parentId  the value for enterprise_info.parent_id
	 * @mbggenerated
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.is_order
	 * @return  the value of enterprise_info.is_order
	 * @mbggenerated
	 */
	public Integer getIsOrder() {
		return isOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.is_order
	 * @param isOrder  the value for enterprise_info.is_order
	 * @mbggenerated
	 */
	public void setIsOrder(Integer isOrder) {
		this.isOrder = isOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.sname
	 * @return  the value of enterprise_info.sname
	 * @mbggenerated
	 */
	public String getSname() {
		return sname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.sname
	 * @param sname  the value for enterprise_info.sname
	 * @mbggenerated
	 */
	public void setSname(String sname) {
		this.sname = sname == null ? null : sname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.s_area
	 * @return  the value of enterprise_info.s_area
	 * @mbggenerated
	 */
	public String getsArea() {
		return sArea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.s_area
	 * @param sArea  the value for enterprise_info.s_area
	 * @mbggenerated
	 */
	public void setsArea(String sArea) {
		this.sArea = sArea == null ? null : sArea.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.t_type
	 * @return  the value of enterprise_info.t_type
	 * @mbggenerated
	 */
	public String gettType() {
		return tType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.t_type
	 * @param tType  the value for enterprise_info.t_type
	 * @mbggenerated
	 */
	public void settType(String tType) {
		this.tType = tType == null ? null : tType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.slevel
	 * @return  the value of enterprise_info.slevel
	 * @mbggenerated
	 */
	public Integer getSlevel() {
		return slevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.slevel
	 * @param slevel  the value for enterprise_info.slevel
	 * @mbggenerated
	 */
	public void setSlevel(Integer slevel) {
		this.slevel = slevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.jg_type
	 * @return  the value of enterprise_info.jg_type
	 * @mbggenerated
	 */
	public String getJgType() {
		return jgType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.jg_type
	 * @param jgType  the value for enterprise_info.jg_type
	 * @mbggenerated
	 */
	public void setJgType(String jgType) {
		this.jgType = jgType == null ? null : jgType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.jj_type
	 * @return  the value of enterprise_info.jj_type
	 * @mbggenerated
	 */
	public String getJjType() {
		return jjType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.jj_type
	 * @param jjType  the value for enterprise_info.jj_type
	 * @mbggenerated
	 */
	public void setJjType(String jjType) {
		this.jjType = jjType == null ? null : jjType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.area
	 * @return  the value of enterprise_info.area
	 * @mbggenerated
	 */
	public String getArea() {
		return area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.area
	 * @param area  the value for enterprise_info.area
	 * @mbggenerated
	 */
	public void setArea(String area) {
		this.area = area == null ? null : area.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.tel
	 * @return  the value of enterprise_info.tel
	 * @mbggenerated
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.tel
	 * @param tel  the value for enterprise_info.tel
	 * @mbggenerated
	 */
	public void setTel(String tel) {
		this.tel = tel == null ? null : tel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.email
	 * @return  the value of enterprise_info.email
	 * @mbggenerated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.email
	 * @param email  the value for enterprise_info.email
	 * @mbggenerated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.up_date
	 * @return  the value of enterprise_info.up_date
	 * @mbggenerated
	 */
	public Date getUpDate() {
		return upDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.up_date
	 * @param upDate  the value for enterprise_info.up_date
	 * @mbggenerated
	 */
	public void setUpDate(Date upDate) {
		this.upDate = upDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.up_type
	 * @return  the value of enterprise_info.up_type
	 * @mbggenerated
	 */
	public String getUpType() {
		return upType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.up_type
	 * @param upType  the value for enterprise_info.up_type
	 * @mbggenerated
	 */
	public void setUpType(String upType) {
		this.upType = upType == null ? null : upType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.up_code
	 * @return  the value of enterprise_info.up_code
	 * @mbggenerated
	 */
	public String getUpCode() {
		return upCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.up_code
	 * @param upCode  the value for enterprise_info.up_code
	 * @mbggenerated
	 */
	public void setUpCode(String upCode) {
		this.upCode = upCode == null ? null : upCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.up_name
	 * @return  the value of enterprise_info.up_name
	 * @mbggenerated
	 */
	public String getUpName() {
		return upName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.up_name
	 * @param upName  the value for enterprise_info.up_name
	 * @mbggenerated
	 */
	public void setUpName(String upName) {
		this.upName = upName == null ? null : upName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.up_uid
	 * @return  the value of enterprise_info.up_uid
	 * @mbggenerated
	 */
	public String getUpUid() {
		return upUid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.up_uid
	 * @param upUid  the value for enterprise_info.up_uid
	 * @mbggenerated
	 */
	public void setUpUid(String upUid) {
		this.upUid = upUid == null ? null : upUid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.up_tel
	 * @return  the value of enterprise_info.up_tel
	 * @mbggenerated
	 */
	public String getUpTel() {
		return upTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.up_tel
	 * @param upTel  the value for enterprise_info.up_tel
	 * @mbggenerated
	 */
	public void setUpTel(String upTel) {
		this.upTel = upTel == null ? null : upTel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.mg_type
	 * @return  the value of enterprise_info.mg_type
	 * @mbggenerated
	 */
	public String getMgType() {
		return mgType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.mg_type
	 * @param mgType  the value for enterprise_info.mg_type
	 * @mbggenerated
	 */
	public void setMgType(String mgType) {
		this.mgType = mgType == null ? null : mgType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.uid
	 * @return  the value of enterprise_info.uid
	 * @mbggenerated
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.uid
	 * @param uid  the value for enterprise_info.uid
	 * @mbggenerated
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.s_msg
	 * @return  the value of enterprise_info.s_msg
	 * @mbggenerated
	 */
	public String getsMsg() {
		return sMsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.s_msg
	 * @param sMsg  the value for enterprise_info.s_msg
	 * @mbggenerated
	 */
	public void setsMsg(String sMsg) {
		this.sMsg = sMsg == null ? null : sMsg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.del_date
	 * @return  the value of enterprise_info.del_date
	 * @mbggenerated
	 */
	public Date getDelDate() {
		return delDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.del_date
	 * @param delDate  the value for enterprise_info.del_date
	 * @mbggenerated
	 */
	public void setDelDate(Date delDate) {
		this.delDate = delDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_info.pwd
	 * @return  the value of enterprise_info.pwd
	 * @mbggenerated
	 */
	public String getPwd() {
		return pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_info.pwd
	 * @param pwd  the value for enterprise_info.pwd
	 * @mbggenerated
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd == null ? null : pwd.trim();
	}

	public int getIsAuthorize() {
		return isAuthorize;
	}

	public void setIsAuthorize(int isAuthorize) {
		this.isAuthorize = isAuthorize;
	}
	
}