package com.i84.earnpoint.model;

import java.util.Date;

public class ExamCertificateInfo extends Page {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam_certificate_info.certificate_id
	 * 
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	private Integer certificateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam_certificate_info.class_num
	 * 
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	private String classNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam_certificate_info.class_name
	 * 
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	private String className;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam_certificate_info.card_id
	 * 
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	private String cardId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam_certificate_info.user_name
	 * 
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam_certificate_info.certificate_type
	 * 
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	private String certificateType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam_certificate_info.certificate_name
	 * 
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	private String certificateName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam_certificate_info.certificate_num
	 * 
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	private String certificateNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam_certificate_info.certificate_time
	 * 
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	private String certificateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam_certificate_info.expiry_date
	 * 
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	private String expiryDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam_certificate_info.create_time
	 * 
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam_certificate_info.status
	 * 
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	private String status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column exam_certificate_info.certificate_id
	 * 
	 * @return the value of exam_certificate_info.certificate_id
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	public Integer getCertificateId() {
		return certificateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column exam_certificate_info.certificate_id
	 * 
	 * @param certificateId
	 *            the value for exam_certificate_info.certificate_id
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	public void setCertificateId(Integer certificateId) {
		this.certificateId = certificateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column exam_certificate_info.class_num
	 * 
	 * @return the value of exam_certificate_info.class_num
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	public String getClassNum() {
		return classNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column exam_certificate_info.class_num
	 * 
	 * @param classNum
	 *            the value for exam_certificate_info.class_num
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	public void setClassNum(String classNum) {
		this.classNum = classNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column exam_certificate_info.class_name
	 * 
	 * @return the value of exam_certificate_info.class_name
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	public String getClassName() {
		return className;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column exam_certificate_info.class_name
	 * 
	 * @param className
	 *            the value for exam_certificate_info.class_name
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	public void setClassName(String className) {
		this.className = className;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column exam_certificate_info.card_id
	 * 
	 * @return the value of exam_certificate_info.card_id
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	public String getCardId() {
		return cardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column exam_certificate_info.card_id
	 * 
	 * @param cardId
	 *            the value for exam_certificate_info.card_id
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	public void setCardId(String cardId) {
		this.cardId = cardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column exam_certificate_info.user_name
	 * 
	 * @return the value of exam_certificate_info.user_name
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column exam_certificate_info.user_name
	 * 
	 * @param userName
	 *            the value for exam_certificate_info.user_name
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column exam_certificate_info.certificate_type
	 * 
	 * @return the value of exam_certificate_info.certificate_type
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	public String getCertificateType() {
		return certificateType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column exam_certificate_info.certificate_type
	 * 
	 * @param certificateType
	 *            the value for exam_certificate_info.certificate_type
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	public void setCertificateType(String certificateType) {
		this.certificateType = certificateType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column exam_certificate_info.certificate_name
	 * 
	 * @return the value of exam_certificate_info.certificate_name
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	public String getCertificateName() {
		return certificateName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column exam_certificate_info.certificate_name
	 * 
	 * @param certificateName
	 *            the value for exam_certificate_info.certificate_name
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	public void setCertificateName(String certificateName) {
		this.certificateName = certificateName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column exam_certificate_info.certificate_num
	 * 
	 * @return the value of exam_certificate_info.certificate_num
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	public String getCertificateNum() {
		return certificateNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column exam_certificate_info.certificate_num
	 * 
	 * @param certificateNum
	 *            the value for exam_certificate_info.certificate_num
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	public void setCertificateNum(String certificateNum) {
		this.certificateNum = certificateNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column exam_certificate_info.certificate_time
	 * 
	 * @return the value of exam_certificate_info.certificate_time
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	public String getCertificateTime() {
		return certificateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column exam_certificate_info.certificate_time
	 * 
	 * @param certificateTime
	 *            the value for exam_certificate_info.certificate_time
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	public void setCertificateTime(String certificateTime) {
		this.certificateTime = certificateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column exam_certificate_info.expiry_date
	 * 
	 * @return the value of exam_certificate_info.expiry_date
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	public String getExpiryDate() {
		return expiryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column exam_certificate_info.expiry_date
	 * 
	 * @param expiryDate
	 *            the value for exam_certificate_info.expiry_date
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	public void setExpiryDate(String expiryDate) {
		this.expiryDate = expiryDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column exam_certificate_info.create_time
	 * 
	 * @return the value of exam_certificate_info.create_time
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column exam_certificate_info.create_time
	 * 
	 * @param createTime
	 *            the value for exam_certificate_info.create_time
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column exam_certificate_info.status
	 * 
	 * @return the value of exam_certificate_info.status
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column exam_certificate_info.status
	 * 
	 * @param status
	 *            the value for exam_certificate_info.status
	 * @mbggenerated Sun Oct 16 11:17:24 CST 2016
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	private String projectName;
	private String certificateTimeBegin;
	private String certificateTimeEnd;
	private String expiryDateBegin;
	private String expiryDateEnd;

	public String getProjectName() {
		return projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getCertificateTimeBegin() {
		return certificateTimeBegin;
	}

	public void setCertificateTimeBegin(String certificateTimeBegin) {
		this.certificateTimeBegin = certificateTimeBegin;
	}

	public String getCertificateTimeEnd() {
		return certificateTimeEnd;
	}

	public void setCertificateTimeEnd(String certificateTimeEnd) {
		this.certificateTimeEnd = certificateTimeEnd;
	}

	public String getExpiryDateBegin() {
		return expiryDateBegin;
	}

	public void setExpiryDateBegin(String expiryDateBegin) {
		this.expiryDateBegin = expiryDateBegin;
	}

	public String getExpiryDateEnd() {
		return expiryDateEnd;
	}

	public void setExpiryDateEnd(String expiryDateEnd) {
		this.expiryDateEnd = expiryDateEnd;
	}

}