package com.i84.earnpoint.model;

import java.io.Serializable;
import java.util.Date;

import com.i84.earnpoint.common.SystemContant;
/**
 * 专业技术职务资格证书
 * @author Administrator
 *
 */
public class PersonMajorCertificate extends Page implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_major_certificate.id
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_major_certificate.approval_date
     * 批注日期
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private String approvalDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_major_certificate.major
     * 专业类别/专业名称
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private String major;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_major_certificate.qualification
     * 资格名称
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private String qualification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_major_certificate.level
     * 级别
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_major_certificate.certificate_number
     * 证书编号
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private String certificateNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_major_certificate.approval_number
     * 批准文号
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private String approvalNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_major_certificate.given_date
     * 发证时间
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private String givenDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_major_certificate.approval_org
     * 审批组织
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private String approvalOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_major_certificate.approval_department
     * 审批部门
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private String approvalDepartment;
    /**
     * 身份证号码
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_major_certificate.pid
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private Integer pid;
    private Date createDate;
    /**
     * 删除状态
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_major_certificate.del_status
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private String delStatus = SystemContant.STATUS_USABLE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_major_certificate.id
     *
     * @return the value of person_major_certificate.id
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_major_certificate.id
     *
     * @param id the value for person_major_certificate.id
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_major_certificate.approval_date
     *
     * @return the value of person_major_certificate.approval_date
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public String getApprovalDate() {
        return approvalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_major_certificate.approval_date
     *
     * @param approvalDate the value for person_major_certificate.approval_date
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public void setApprovalDate(String approvalDate) {
        this.approvalDate = approvalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_major_certificate.major
     *
     * @return the value of person_major_certificate.major
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_major_certificate.major
     *
     * @param major the value for person_major_certificate.major
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_major_certificate.qualification
     *
     * @return the value of person_major_certificate.qualification
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public String getQualification() {
        return qualification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_major_certificate.qualification
     *
     * @param qualification the value for person_major_certificate.qualification
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public void setQualification(String qualification) {
        this.qualification = qualification == null ? null : qualification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_major_certificate.level
     *
     * @return the value of person_major_certificate.level
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_major_certificate.level
     *
     * @param level the value for person_major_certificate.level
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_major_certificate.certificate_number
     *
     * @return the value of person_major_certificate.certificate_number
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public String getCertificateNumber() {
        return certificateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_major_certificate.certificate_number
     *
     * @param certificateNumber the value for person_major_certificate.certificate_number
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public void setCertificateNumber(String certificateNumber) {
        this.certificateNumber = certificateNumber == null ? null : certificateNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_major_certificate.approval_number
     *
     * @return the value of person_major_certificate.approval_number
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public String getApprovalNumber() {
        return approvalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_major_certificate.approval_number
     *
     * @param approvalNumber the value for person_major_certificate.approval_number
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public void setApprovalNumber(String approvalNumber) {
        this.approvalNumber = approvalNumber == null ? null : approvalNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_major_certificate.given_date
     *
     * @return the value of person_major_certificate.given_date
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public String getGivenDate() {
        return givenDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_major_certificate.given_date
     *
     * @param givenDate the value for person_major_certificate.given_date
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public void setGivenDate(String givenDate) {
        this.givenDate = givenDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_major_certificate.approval_org
     *
     * @return the value of person_major_certificate.approval_org
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public String getApprovalOrg() {
        return approvalOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_major_certificate.approval_org
     *
     * @param approvalOrg the value for person_major_certificate.approval_org
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public void setApprovalOrg(String approvalOrg) {
        this.approvalOrg = approvalOrg == null ? null : approvalOrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_major_certificate.approval_department
     *
     * @return the value of person_major_certificate.approval_department
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public String getApprovalDepartment() {
        return approvalDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_major_certificate.approval_department
     *
     * @param approvalDepartment the value for person_major_certificate.approval_department
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public void setApprovalDepartment(String approvalDepartment) {
        this.approvalDepartment = approvalDepartment == null ? null : approvalDepartment.trim();
    }

	

	public Integer getPid() {
		return pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getDelStatus() {
		return delStatus;
	}

	public void setDelStatus(String delStatus) {
		this.delStatus = delStatus;
	}
    
}