package com.i84.earnpoint.model;

import java.io.Serializable;
import java.util.Date;

import com.i84.earnpoint.common.SystemContant;

/**
 * 奖惩情况
 * @author Administrator
 *
 */
public class PersonReward extends Page implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_reward.id
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_reward.approval_date
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private String approvalDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_reward.reward_name
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private String rewardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_reward.reward_level
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private String rewardLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_reward.description
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private String description;
    /**
     * 身份证号码
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_reward.pid
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private Integer pid;
    private Date createDate;
    /**
     * 删除状态
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_reward.del_status
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private String delStatus = SystemContant.STATUS_USABLE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_reward.id
     *
     * @return the value of person_reward.id
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_reward.id
     *
     * @param id the value for person_reward.id
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_reward.approval_date
     *
     * @return the value of person_reward.approval_date
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public String getApprovalDate() {
        return approvalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_reward.approval_date
     *
     * @param approvalDate the value for person_reward.approval_date
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public void setApprovalDate(String approvalDate) {
        this.approvalDate = approvalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_reward.reward_name
     *
     * @return the value of person_reward.reward_name
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public String getRewardName() {
        return rewardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_reward.reward_name
     *
     * @param rewardName the value for person_reward.reward_name
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public void setRewardName(String rewardName) {
        this.rewardName = rewardName == null ? null : rewardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_reward.reward_level
     *
     * @return the value of person_reward.reward_level
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public String getRewardLevel() {
        return rewardLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_reward.reward_level
     *
     * @param rewardLevel the value for person_reward.reward_level
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public void setRewardLevel(String rewardLevel) {
        this.rewardLevel = rewardLevel == null ? null : rewardLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_reward.description
     *
     * @return the value of person_reward.description
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_reward.description
     *
     * @param description the value for person_reward.description
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

	

	public Integer getPid() {
		return pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getDelStatus() {
		return delStatus;
	}

	public void setDelStatus(String delStatus) {
		this.delStatus = delStatus;
	}
    
    
}