package com.i84.earnpoint.model;

import java.io.Serializable;
import java.util.Date;

import com.i84.earnpoint.common.SystemContant;

/**
 * 学习经历
 * @author Administrator
 *
 */
public class PersonEducationInfo extends Page implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_education_info.id
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private Integer id;

    /**
     * 毕业日期
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_education_info.graduate_date
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private String graduateDate;

    /**
     * 学校名称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_education_info.school_name
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private String schoolName;

    /**
     * 学历
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_education_info.education
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private String education;

    /**
     * 专业
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_education_info.major
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private String major;

    /**
     * 学位
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_education_info.degree
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private String degree;
    /**
     * 身份证号码
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_education_info.pid
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private Integer pid;
    private Date createDate;
    /**
     * 删除状态
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_education_info.del_status
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private String delStatus = SystemContant.STATUS_USABLE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_education_info.id
     *
     * @return the value of person_education_info.id
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_education_info.id
     *
     * @param id the value for person_education_info.id
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_education_info.graduate_date
     *
     * @return the value of person_education_info.graduate_date
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public String getGraduateDate() {
        return graduateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_education_info.graduate_date
     *
     * @param graduateDate the value for person_education_info.graduate_date
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public void setGraduateDate(String graduateDate) {
        this.graduateDate = graduateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_education_info.school_name
     *
     * @return the value of person_education_info.school_name
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_education_info.school_name
     *
     * @param schoolName the value for person_education_info.school_name
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_education_info.education
     *
     * @return the value of person_education_info.education
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_education_info.education
     *
     * @param education the value for person_education_info.education
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_education_info.major
     *
     * @return the value of person_education_info.major
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_education_info.major
     *
     * @param major the value for person_education_info.major
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_education_info.degree
     *
     * @return the value of person_education_info.degree
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_education_info.degree
     *
     * @param degree the value for person_education_info.degree
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

	public Integer getPid() {
		return pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getDelStatus() {
		return delStatus;
	}

	public void setDelStatus(String delStatus) {
		this.delStatus = delStatus;
	}
    
    
}