package com.i84.earnpoint.model;

import java.util.Date;

public class StudyUpInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study_up_info.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study_up_info.uid
	 * @mbggenerated
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study_up_info.training_unit
	 * @mbggenerated
	 */
	private String trainingUnit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study_up_info.train_date
	 * @mbggenerated
	 */
	private String trainDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study_up_info.out_date
	 * @mbggenerated
	 */
	private String outDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study_up_info.train_no
	 * @mbggenerated
	 */
	private String trainNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study_up_info.office
	 * @mbggenerated
	 */
	private String office;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study_up_info.office_date
	 * @mbggenerated
	 */
	private String officeDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study_up_info.del_date
	 * @mbggenerated
	 */
	private Date delDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study_up_info.study_time
	 * @mbggenerated
	 */
	private String studyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study_up_info.study_method
	 * @mbggenerated
	 */
	private String studyMethod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study_up_info.study_content
	 * @mbggenerated
	 */
	private String studyContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study_up_info.activity_id
	 * @mbggenerated
	 */
	private Integer activityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study_up_info.add_date
	 * @mbggenerated
	 */
	private Date addDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column study_up_info.pid
	 * @mbggenerated
	 */
	private Integer pid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study_up_info.id
	 * @return  the value of study_up_info.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study_up_info.id
	 * @param id  the value for study_up_info.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study_up_info.uid
	 * @return  the value of study_up_info.uid
	 * @mbggenerated
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study_up_info.uid
	 * @param uid  the value for study_up_info.uid
	 * @mbggenerated
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study_up_info.training_unit
	 * @return  the value of study_up_info.training_unit
	 * @mbggenerated
	 */
	public String getTrainingUnit() {
		return trainingUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study_up_info.training_unit
	 * @param trainingUnit  the value for study_up_info.training_unit
	 * @mbggenerated
	 */
	public void setTrainingUnit(String trainingUnit) {
		this.trainingUnit = trainingUnit == null ? null : trainingUnit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study_up_info.train_date
	 * @return  the value of study_up_info.train_date
	 * @mbggenerated
	 */
	public String getTrainDate() {
		return trainDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study_up_info.train_date
	 * @param trainDate  the value for study_up_info.train_date
	 * @mbggenerated
	 */
	public void setTrainDate(String trainDate) {
		this.trainDate = trainDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study_up_info.out_date
	 * @return  the value of study_up_info.out_date
	 * @mbggenerated
	 */
	public String getOutDate() {
		return outDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study_up_info.out_date
	 * @param outDate  the value for study_up_info.out_date
	 * @mbggenerated
	 */
	public void setOutDate(String outDate) {
		this.outDate = outDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study_up_info.train_no
	 * @return  the value of study_up_info.train_no
	 * @mbggenerated
	 */
	public String getTrainNo() {
		return trainNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study_up_info.train_no
	 * @param trainNo  the value for study_up_info.train_no
	 * @mbggenerated
	 */
	public void setTrainNo(String trainNo) {
		this.trainNo = trainNo == null ? null : trainNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study_up_info.office
	 * @return  the value of study_up_info.office
	 * @mbggenerated
	 */
	public String getOffice() {
		return office;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study_up_info.office
	 * @param office  the value for study_up_info.office
	 * @mbggenerated
	 */
	public void setOffice(String office) {
		this.office = office == null ? null : office.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study_up_info.office_date
	 * @return  the value of study_up_info.office_date
	 * @mbggenerated
	 */
	public String getOfficeDate() {
		return officeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study_up_info.office_date
	 * @param officeDate  the value for study_up_info.office_date
	 * @mbggenerated
	 */
	public void setOfficeDate(String officeDate) {
		this.officeDate = officeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study_up_info.del_date
	 * @return  the value of study_up_info.del_date
	 * @mbggenerated
	 */
	public Date getDelDate() {
		return delDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study_up_info.del_date
	 * @param delDate  the value for study_up_info.del_date
	 * @mbggenerated
	 */
	public void setDelDate(Date delDate) {
		this.delDate = delDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study_up_info.study_time
	 * @return  the value of study_up_info.study_time
	 * @mbggenerated
	 */
	public String getStudyTime() {
		return studyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study_up_info.study_time
	 * @param studyTime  the value for study_up_info.study_time
	 * @mbggenerated
	 */
	public void setStudyTime(String studyTime) {
		this.studyTime = studyTime == null ? null : studyTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study_up_info.study_method
	 * @return  the value of study_up_info.study_method
	 * @mbggenerated
	 */
	public String getStudyMethod() {
		return studyMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study_up_info.study_method
	 * @param studyMethod  the value for study_up_info.study_method
	 * @mbggenerated
	 */
	public void setStudyMethod(String studyMethod) {
		this.studyMethod = studyMethod == null ? null : studyMethod.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study_up_info.study_content
	 * @return  the value of study_up_info.study_content
	 * @mbggenerated
	 */
	public String getStudyContent() {
		return studyContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study_up_info.study_content
	 * @param studyContent  the value for study_up_info.study_content
	 * @mbggenerated
	 */
	public void setStudyContent(String studyContent) {
		this.studyContent = studyContent == null ? null : studyContent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study_up_info.activity_id
	 * @return  the value of study_up_info.activity_id
	 * @mbggenerated
	 */
	public Integer getActivityId() {
		return activityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study_up_info.activity_id
	 * @param activityId  the value for study_up_info.activity_id
	 * @mbggenerated
	 */
	public void setActivityId(Integer activityId) {
		this.activityId = activityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study_up_info.add_date
	 * @return  the value of study_up_info.add_date
	 * @mbggenerated
	 */
	public Date getAddDate() {
		return addDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study_up_info.add_date
	 * @param addDate  the value for study_up_info.add_date
	 * @mbggenerated
	 */
	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column study_up_info.pid
	 * @return  the value of study_up_info.pid
	 * @mbggenerated
	 */
	public Integer getPid() {
		if(pid==null)
			return 0;
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column study_up_info.pid
	 * @param pid  the value for study_up_info.pid
	 * @mbggenerated
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}
}