package com.i84.earnpoint.model;

import java.io.Serializable;
import java.util.Date;

import com.i84.earnpoint.model.Page;

public class UnitInfo extends Page implements Serializable{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.id
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.org_code
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private String orgCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.org_name
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private String orgName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.other_name
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private String otherName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.competent_department
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private String competentDepartment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.approval_number
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private String approvalNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.establish_time
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private Date establishTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.unit_nature
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private String unitNature;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.unit_level
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private String unitLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.funds_source
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private String fundsSource;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.industry_involved
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private String industryInvolved;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.corporate_representative
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private String corporateRepresentative;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.unit_all_number
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private Integer unitAllNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.unit_now_number
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private Integer unitNowNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.code_number
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private String codeNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.unit_address
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private String unitAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.postal_code
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private String postalCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.branched_leader
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private String branchedLeader;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.branched_leader_phone
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private String branchedLeaderPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.branched_leader_mobile
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private String branchedLeaderMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.branched_leader_email
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private String branchedLeaderEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.personnel_leader
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private String personnelLeader;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.personnel_leader_phone
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private String personnelLeaderPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.personnel_leader_mobile
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private String personnelLeaderMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.personnel_leader_email
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private String personnelLeaderEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.personnel_leader_fax
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private String personnelLeaderFax;
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.status
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.uid
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column unit_info.content
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.id
	 * @return  the value of unit_info.id
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.id
	 * @param id  the value for unit_info.id
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.org_code
	 * @return  the value of unit_info.org_code
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public String getOrgCode() {
		return orgCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.org_code
	 * @param orgCode  the value for unit_info.org_code
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode == null ? null : orgCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.org_name
	 * @return  the value of unit_info.org_name
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public String getOrgName() {
		return orgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.org_name
	 * @param orgName  the value for unit_info.org_name
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setOrgName(String orgName) {
		this.orgName = orgName == null ? null : orgName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.other_name
	 * @return  the value of unit_info.other_name
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public String getOtherName() {
		return otherName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.other_name
	 * @param otherName  the value for unit_info.other_name
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setOtherName(String otherName) {
		this.otherName = otherName == null ? null : otherName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.competent_department
	 * @return  the value of unit_info.competent_department
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public String getCompetentDepartment() {
		return competentDepartment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.competent_department
	 * @param competentDepartment  the value for unit_info.competent_department
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setCompetentDepartment(String competentDepartment) {
		this.competentDepartment = competentDepartment == null ? null : competentDepartment.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.approval_number
	 * @return  the value of unit_info.approval_number
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public String getApprovalNumber() {
		return approvalNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.approval_number
	 * @param approvalNumber  the value for unit_info.approval_number
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setApprovalNumber(String approvalNumber) {
		this.approvalNumber = approvalNumber == null ? null : approvalNumber.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.establish_time
	 * @return  the value of unit_info.establish_time
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public Date getEstablishTime() {
		return establishTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.establish_time
	 * @param establishTime  the value for unit_info.establish_time
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setEstablishTime(Date establishTime) {
		this.establishTime = establishTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.unit_nature
	 * @return  the value of unit_info.unit_nature
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public String getUnitNature() {
		return unitNature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.unit_nature
	 * @param unitNature  the value for unit_info.unit_nature
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setUnitNature(String unitNature) {
		this.unitNature = unitNature == null ? null : unitNature.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.unit_level
	 * @return  the value of unit_info.unit_level
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public String getUnitLevel() {
		return unitLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.unit_level
	 * @param unitLevel  the value for unit_info.unit_level
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setUnitLevel(String unitLevel) {
		this.unitLevel = unitLevel == null ? null : unitLevel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.funds_source
	 * @return  the value of unit_info.funds_source
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public String getFundsSource() {
		return fundsSource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.funds_source
	 * @param fundsSource  the value for unit_info.funds_source
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setFundsSource(String fundsSource) {
		this.fundsSource = fundsSource == null ? null : fundsSource.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.industry_involved
	 * @return  the value of unit_info.industry_involved
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public String getIndustryInvolved() {
		return industryInvolved;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.industry_involved
	 * @param industryInvolved  the value for unit_info.industry_involved
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setIndustryInvolved(String industryInvolved) {
		this.industryInvolved = industryInvolved == null ? null : industryInvolved.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.corporate_representative
	 * @return  the value of unit_info.corporate_representative
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public String getCorporateRepresentative() {
		return corporateRepresentative;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.corporate_representative
	 * @param corporateRepresentative  the value for unit_info.corporate_representative
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setCorporateRepresentative(String corporateRepresentative) {
		this.corporateRepresentative = corporateRepresentative == null ? null : corporateRepresentative.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.unit_all_number
	 * @return  the value of unit_info.unit_all_number
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public Integer getUnitAllNumber() {
		return unitAllNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.unit_all_number
	 * @param unitAllNumber  the value for unit_info.unit_all_number
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setUnitAllNumber(Integer unitAllNumber) {
		this.unitAllNumber = unitAllNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.unit_now_number
	 * @return  the value of unit_info.unit_now_number
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public Integer getUnitNowNumber() {
		return unitNowNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.unit_now_number
	 * @param unitNowNumber  the value for unit_info.unit_now_number
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setUnitNowNumber(Integer unitNowNumber) {
		this.unitNowNumber = unitNowNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.code_number
	 * @return  the value of unit_info.code_number
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public String getCodeNumber() {
		return codeNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.code_number
	 * @param codeNumber  the value for unit_info.code_number
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setCodeNumber(String codeNumber) {
		this.codeNumber = codeNumber == null ? null : codeNumber.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.unit_address
	 * @return  the value of unit_info.unit_address
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public String getUnitAddress() {
		return unitAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.unit_address
	 * @param unitAddress  the value for unit_info.unit_address
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setUnitAddress(String unitAddress) {
		this.unitAddress = unitAddress == null ? null : unitAddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.postal_code
	 * @return  the value of unit_info.postal_code
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public String getPostalCode() {
		return postalCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.postal_code
	 * @param postalCode  the value for unit_info.postal_code
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode == null ? null : postalCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.branched_leader
	 * @return  the value of unit_info.branched_leader
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public String getBranchedLeader() {
		return branchedLeader;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.branched_leader
	 * @param branchedLeader  the value for unit_info.branched_leader
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setBranchedLeader(String branchedLeader) {
		this.branchedLeader = branchedLeader == null ? null : branchedLeader.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.branched_leader_phone
	 * @return  the value of unit_info.branched_leader_phone
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public String getBranchedLeaderPhone() {
		return branchedLeaderPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.branched_leader_phone
	 * @param branchedLeaderPhone  the value for unit_info.branched_leader_phone
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setBranchedLeaderPhone(String branchedLeaderPhone) {
		this.branchedLeaderPhone = branchedLeaderPhone == null ? null : branchedLeaderPhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.branched_leader_mobile
	 * @return  the value of unit_info.branched_leader_mobile
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public String getBranchedLeaderMobile() {
		return branchedLeaderMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.branched_leader_mobile
	 * @param branchedLeaderMobile  the value for unit_info.branched_leader_mobile
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setBranchedLeaderMobile(String branchedLeaderMobile) {
		this.branchedLeaderMobile = branchedLeaderMobile == null ? null : branchedLeaderMobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.branched_leader_email
	 * @return  the value of unit_info.branched_leader_email
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public String getBranchedLeaderEmail() {
		return branchedLeaderEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.branched_leader_email
	 * @param branchedLeaderEmail  the value for unit_info.branched_leader_email
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setBranchedLeaderEmail(String branchedLeaderEmail) {
		this.branchedLeaderEmail = branchedLeaderEmail == null ? null : branchedLeaderEmail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.personnel_leader
	 * @return  the value of unit_info.personnel_leader
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public String getPersonnelLeader() {
		return personnelLeader;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.personnel_leader
	 * @param personnelLeader  the value for unit_info.personnel_leader
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setPersonnelLeader(String personnelLeader) {
		this.personnelLeader = personnelLeader == null ? null : personnelLeader.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.personnel_leader_phone
	 * @return  the value of unit_info.personnel_leader_phone
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public String getPersonnelLeaderPhone() {
		return personnelLeaderPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.personnel_leader_phone
	 * @param personnelLeaderPhone  the value for unit_info.personnel_leader_phone
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setPersonnelLeaderPhone(String personnelLeaderPhone) {
		this.personnelLeaderPhone = personnelLeaderPhone == null ? null : personnelLeaderPhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.personnel_leader_mobile
	 * @return  the value of unit_info.personnel_leader_mobile
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public String getPersonnelLeaderMobile() {
		return personnelLeaderMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.personnel_leader_mobile
	 * @param personnelLeaderMobile  the value for unit_info.personnel_leader_mobile
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setPersonnelLeaderMobile(String personnelLeaderMobile) {
		this.personnelLeaderMobile = personnelLeaderMobile == null ? null : personnelLeaderMobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.personnel_leader_email
	 * @return  the value of unit_info.personnel_leader_email
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public String getPersonnelLeaderEmail() {
		return personnelLeaderEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.personnel_leader_email
	 * @param personnelLeaderEmail  the value for unit_info.personnel_leader_email
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setPersonnelLeaderEmail(String personnelLeaderEmail) {
		this.personnelLeaderEmail = personnelLeaderEmail == null ? null : personnelLeaderEmail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.personnel_leader_fax
	 * @return  the value of unit_info.personnel_leader_fax
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public String getPersonnelLeaderFax() {
		return personnelLeaderFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.personnel_leader_fax
	 * @param personnelLeaderFax  the value for unit_info.personnel_leader_fax
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setPersonnelLeaderFax(String personnelLeaderFax) {
		this.personnelLeaderFax = personnelLeaderFax == null ? null : personnelLeaderFax.trim();
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.status
	 * @return  the value of unit_info.status
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.status
	 * @param status  the value for unit_info.status
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.uid
	 * @return  the value of unit_info.uid
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.uid
	 * @param uid  the value for unit_info.uid
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column unit_info.content
	 * @return  the value of unit_info.content
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column unit_info.content
	 * @param content  the value for unit_info.content
	 * @mbggenerated  Sat Oct 22 11:01:08 CST 2016
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}
}