package com.i84.earnpoint.model;

import java.util.Date;

public class UserMgInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.uid
	 * @mbggenerated
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.msgfrom
	 * @mbggenerated
	 */
	private String msgfrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.is_state
	 * @mbggenerated
	 */
	private String isState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.smsg
	 * @mbggenerated
	 */
	private String smsg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.dtype
	 * @mbggenerated
	 */
	private String dtype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.dpno
	 * @mbggenerated
	 */
	private String dpno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.is_s
	 * @mbggenerated
	 */
	private String isS;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.bd_unit
	 * @mbggenerated
	 */
	private String bdUnit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.sp_date
	 * @mbggenerated
	 */
	private Date spDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.unit_adr
	 * @mbggenerated
	 */
	private String unitAdr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.bpno
	 * @mbggenerated
	 */
	private String bpno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.ctype
	 * @mbggenerated
	 */
	private String ctype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.license
	 * @mbggenerated
	 */
	private String license;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.home_tel
	 * @mbggenerated
	 */
	private String homeTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.home_adr
	 * @mbggenerated
	 */
	private String homeAdr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.home_post
	 * @mbggenerated
	 */
	private String homePost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.my_tel
	 * @mbggenerated
	 */
	private String myTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.my_adr
	 * @mbggenerated
	 */
	private String myAdr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.my_post
	 * @mbggenerated
	 */
	private String myPost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.wife_name
	 * @mbggenerated
	 */
	private String wifeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.wife_tel
	 * @mbggenerated
	 */
	private String wifeTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.create_date
	 * @mbggenerated
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.out_date
	 * @mbggenerated
	 */
	private Date outDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.del_date
	 * @mbggenerated
	 */
	private Date delDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.point_proxy
	 * @mbggenerated
	 */
	private String pointProxy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.human_out
	 * @mbggenerated
	 */
	private String humanOut;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.is_ad
	 * @mbggenerated
	 */
	private String isAd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.pno
	 * @mbggenerated
	 */
	private String pno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.human_out1
	 * @mbggenerated
	 */
	private String humanOut1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.is_s1
	 * @mbggenerated
	 */
	private String isS1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_mg_info.point_proxy1
	 * @mbggenerated
	 */
	private String pointProxy1;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.id
	 * @return  the value of user_mg_info.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.id
	 * @param id  the value for user_mg_info.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.uid
	 * @return  the value of user_mg_info.uid
	 * @mbggenerated
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.uid
	 * @param uid  the value for user_mg_info.uid
	 * @mbggenerated
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.msgfrom
	 * @return  the value of user_mg_info.msgfrom
	 * @mbggenerated
	 */
	public String getMsgfrom() {
		return msgfrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.msgfrom
	 * @param msgfrom  the value for user_mg_info.msgfrom
	 * @mbggenerated
	 */
	public void setMsgfrom(String msgfrom) {
		this.msgfrom = msgfrom == null ? null : msgfrom.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.is_state
	 * @return  the value of user_mg_info.is_state
	 * @mbggenerated
	 */
	public String getIsState() {
		return isState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.is_state
	 * @param isState  the value for user_mg_info.is_state
	 * @mbggenerated
	 */
	public void setIsState(String isState) {
		this.isState = isState == null ? null : isState.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.smsg
	 * @return  the value of user_mg_info.smsg
	 * @mbggenerated
	 */
	public String getSmsg() {
		return smsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.smsg
	 * @param smsg  the value for user_mg_info.smsg
	 * @mbggenerated
	 */
	public void setSmsg(String smsg) {
		this.smsg = smsg == null ? null : smsg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.dtype
	 * @return  the value of user_mg_info.dtype
	 * @mbggenerated
	 */
	public String getDtype() {
		return dtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.dtype
	 * @param dtype  the value for user_mg_info.dtype
	 * @mbggenerated
	 */
	public void setDtype(String dtype) {
		this.dtype = dtype == null ? null : dtype.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.dpno
	 * @return  the value of user_mg_info.dpno
	 * @mbggenerated
	 */
	public String getDpno() {
		return dpno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.dpno
	 * @param dpno  the value for user_mg_info.dpno
	 * @mbggenerated
	 */
	public void setDpno(String dpno) {
		this.dpno = dpno == null ? null : dpno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.is_s
	 * @return  the value of user_mg_info.is_s
	 * @mbggenerated
	 */
	public String getIsS() {
		return isS;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.is_s
	 * @param isS  the value for user_mg_info.is_s
	 * @mbggenerated
	 */
	public void setIsS(String isS) {
		this.isS = isS == null ? null : isS.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.bd_unit
	 * @return  the value of user_mg_info.bd_unit
	 * @mbggenerated
	 */
	public String getBdUnit() {
		return bdUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.bd_unit
	 * @param bdUnit  the value for user_mg_info.bd_unit
	 * @mbggenerated
	 */
	public void setBdUnit(String bdUnit) {
		this.bdUnit = bdUnit == null ? null : bdUnit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.sp_date
	 * @return  the value of user_mg_info.sp_date
	 * @mbggenerated
	 */
	public Date getSpDate() {
		return spDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.sp_date
	 * @param spDate  the value for user_mg_info.sp_date
	 * @mbggenerated
	 */
	public void setSpDate(Date spDate) {
		this.spDate = spDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.unit_adr
	 * @return  the value of user_mg_info.unit_adr
	 * @mbggenerated
	 */
	public String getUnitAdr() {
		return unitAdr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.unit_adr
	 * @param unitAdr  the value for user_mg_info.unit_adr
	 * @mbggenerated
	 */
	public void setUnitAdr(String unitAdr) {
		this.unitAdr = unitAdr == null ? null : unitAdr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.bpno
	 * @return  the value of user_mg_info.bpno
	 * @mbggenerated
	 */
	public String getBpno() {
		return bpno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.bpno
	 * @param bpno  the value for user_mg_info.bpno
	 * @mbggenerated
	 */
	public void setBpno(String bpno) {
		this.bpno = bpno == null ? null : bpno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.ctype
	 * @return  the value of user_mg_info.ctype
	 * @mbggenerated
	 */
	public String getCtype() {
		return ctype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.ctype
	 * @param ctype  the value for user_mg_info.ctype
	 * @mbggenerated
	 */
	public void setCtype(String ctype) {
		this.ctype = ctype == null ? null : ctype.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.license
	 * @return  the value of user_mg_info.license
	 * @mbggenerated
	 */
	public String getLicense() {
		return license;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.license
	 * @param license  the value for user_mg_info.license
	 * @mbggenerated
	 */
	public void setLicense(String license) {
		this.license = license == null ? null : license.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.home_tel
	 * @return  the value of user_mg_info.home_tel
	 * @mbggenerated
	 */
	public String getHomeTel() {
		return homeTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.home_tel
	 * @param homeTel  the value for user_mg_info.home_tel
	 * @mbggenerated
	 */
	public void setHomeTel(String homeTel) {
		this.homeTel = homeTel == null ? null : homeTel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.home_adr
	 * @return  the value of user_mg_info.home_adr
	 * @mbggenerated
	 */
	public String getHomeAdr() {
		return homeAdr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.home_adr
	 * @param homeAdr  the value for user_mg_info.home_adr
	 * @mbggenerated
	 */
	public void setHomeAdr(String homeAdr) {
		this.homeAdr = homeAdr == null ? null : homeAdr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.home_post
	 * @return  the value of user_mg_info.home_post
	 * @mbggenerated
	 */
	public String getHomePost() {
		return homePost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.home_post
	 * @param homePost  the value for user_mg_info.home_post
	 * @mbggenerated
	 */
	public void setHomePost(String homePost) {
		this.homePost = homePost == null ? null : homePost.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.my_tel
	 * @return  the value of user_mg_info.my_tel
	 * @mbggenerated
	 */
	public String getMyTel() {
		return myTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.my_tel
	 * @param myTel  the value for user_mg_info.my_tel
	 * @mbggenerated
	 */
	public void setMyTel(String myTel) {
		this.myTel = myTel == null ? null : myTel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.my_adr
	 * @return  the value of user_mg_info.my_adr
	 * @mbggenerated
	 */
	public String getMyAdr() {
		return myAdr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.my_adr
	 * @param myAdr  the value for user_mg_info.my_adr
	 * @mbggenerated
	 */
	public void setMyAdr(String myAdr) {
		this.myAdr = myAdr == null ? null : myAdr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.my_post
	 * @return  the value of user_mg_info.my_post
	 * @mbggenerated
	 */
	public String getMyPost() {
		return myPost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.my_post
	 * @param myPost  the value for user_mg_info.my_post
	 * @mbggenerated
	 */
	public void setMyPost(String myPost) {
		this.myPost = myPost == null ? null : myPost.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.wife_name
	 * @return  the value of user_mg_info.wife_name
	 * @mbggenerated
	 */
	public String getWifeName() {
		return wifeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.wife_name
	 * @param wifeName  the value for user_mg_info.wife_name
	 * @mbggenerated
	 */
	public void setWifeName(String wifeName) {
		this.wifeName = wifeName == null ? null : wifeName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.wife_tel
	 * @return  the value of user_mg_info.wife_tel
	 * @mbggenerated
	 */
	public String getWifeTel() {
		return wifeTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.wife_tel
	 * @param wifeTel  the value for user_mg_info.wife_tel
	 * @mbggenerated
	 */
	public void setWifeTel(String wifeTel) {
		this.wifeTel = wifeTel == null ? null : wifeTel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.create_date
	 * @return  the value of user_mg_info.create_date
	 * @mbggenerated
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.create_date
	 * @param createDate  the value for user_mg_info.create_date
	 * @mbggenerated
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.out_date
	 * @return  the value of user_mg_info.out_date
	 * @mbggenerated
	 */
	public Date getOutDate() {
		return outDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.out_date
	 * @param outDate  the value for user_mg_info.out_date
	 * @mbggenerated
	 */
	public void setOutDate(Date outDate) {
		this.outDate = outDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.del_date
	 * @return  the value of user_mg_info.del_date
	 * @mbggenerated
	 */
	public Date getDelDate() {
		return delDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.del_date
	 * @param delDate  the value for user_mg_info.del_date
	 * @mbggenerated
	 */
	public void setDelDate(Date delDate) {
		this.delDate = delDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.point_proxy
	 * @return  the value of user_mg_info.point_proxy
	 * @mbggenerated
	 */
	public String getPointProxy() {
		return pointProxy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.point_proxy
	 * @param pointProxy  the value for user_mg_info.point_proxy
	 * @mbggenerated
	 */
	public void setPointProxy(String pointProxy) {
		this.pointProxy = pointProxy == null ? null : pointProxy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.human_out
	 * @return  the value of user_mg_info.human_out
	 * @mbggenerated
	 */
	public String getHumanOut() {
		return humanOut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.human_out
	 * @param humanOut  the value for user_mg_info.human_out
	 * @mbggenerated
	 */
	public void setHumanOut(String humanOut) {
		this.humanOut = humanOut == null ? null : humanOut.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.is_ad
	 * @return  the value of user_mg_info.is_ad
	 * @mbggenerated
	 */
	public String getIsAd() {
		return isAd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.is_ad
	 * @param isAd  the value for user_mg_info.is_ad
	 * @mbggenerated
	 */
	public void setIsAd(String isAd) {
		this.isAd = isAd == null ? null : isAd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.pno
	 * @return  the value of user_mg_info.pno
	 * @mbggenerated
	 */
	public String getPno() {
		return pno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.pno
	 * @param pno  the value for user_mg_info.pno
	 * @mbggenerated
	 */
	public void setPno(String pno) {
		this.pno = pno == null ? null : pno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.human_out1
	 * @return  the value of user_mg_info.human_out1
	 * @mbggenerated
	 */
	public String getHumanOut1() {
		return humanOut1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.human_out1
	 * @param humanOut1  the value for user_mg_info.human_out1
	 * @mbggenerated
	 */
	public void setHumanOut1(String humanOut1) {
		this.humanOut1 = humanOut1 == null ? null : humanOut1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.is_s1
	 * @return  the value of user_mg_info.is_s1
	 * @mbggenerated
	 */
	public String getIsS1() {
		return isS1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.is_s1
	 * @param isS1  the value for user_mg_info.is_s1
	 * @mbggenerated
	 */
	public void setIsS1(String isS1) {
		this.isS1 = isS1 == null ? null : isS1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_mg_info.point_proxy1
	 * @return  the value of user_mg_info.point_proxy1
	 * @mbggenerated
	 */
	public String getPointProxy1() {
		return pointProxy1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_mg_info.point_proxy1
	 * @param pointProxy1  the value for user_mg_info.point_proxy1
	 * @mbggenerated
	 */
	public void setPointProxy1(String pointProxy1) {
		this.pointProxy1 = pointProxy1 == null ? null : pointProxy1.trim();
	}
}