package com.i84.earnpoint.model;


import com.i84.earnpoint.model.Page;
import java.util.Date;
/**
 * 用户报名bean
 * @author wangsc
 *
 */
public class UserBgInfo implements java.io.Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_bg_info.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_bg_info.user_id
	 * @mbggenerated
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_bg_info.bg_department_id
	 * @mbggenerated
	 */
	private String bgDepartmentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_bg_info.bg_enterpriser_id
	 * @mbggenerated
	 */
	private Integer bgEnterpriserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_bg_info.bg_activity_id
	 * @mbggenerated
	 */
	private Integer bgActivityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_bg_info.is_state
	 * @mbggenerated
	 */
	private String isState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_bg_info.rs
	 * @mbggenerated
	 */
	private String rs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_bg_info.up_state
	 * @mbggenerated
	 */
	private String upState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_bg_info.class_id
	 * @mbggenerated
	 */
	private Integer classId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_bg_info.del_date
	 * @mbggenerated
	 */
	private Date delDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_bg_info.id
	 * @return  the value of user_bg_info.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_bg_info.id
	 * @param id  the value for user_bg_info.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_bg_info.user_id
	 * @return  the value of user_bg_info.user_id
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_bg_info.user_id
	 * @param userId  the value for user_bg_info.user_id
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_bg_info.bg_department_id
	 * @return  the value of user_bg_info.bg_department_id
	 * @mbggenerated
	 */
	public String getBgDepartmentId() {
		return bgDepartmentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_bg_info.bg_department_id
	 * @param bgDepartmentId  the value for user_bg_info.bg_department_id
	 * @mbggenerated
	 */
	public void setBgDepartmentId(String bgDepartmentId) {
		this.bgDepartmentId = bgDepartmentId == null ? null : bgDepartmentId
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_bg_info.bg_enterpriser_id
	 * @return  the value of user_bg_info.bg_enterpriser_id
	 * @mbggenerated
	 */
	public Integer getBgEnterpriserId() {
		return bgEnterpriserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_bg_info.bg_enterpriser_id
	 * @param bgEnterpriserId  the value for user_bg_info.bg_enterpriser_id
	 * @mbggenerated
	 */
	public void setBgEnterpriserId(Integer bgEnterpriserId) {
		this.bgEnterpriserId = bgEnterpriserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_bg_info.bg_activity_id
	 * @return  the value of user_bg_info.bg_activity_id
	 * @mbggenerated
	 */
	public Integer getBgActivityId() {
		return bgActivityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_bg_info.bg_activity_id
	 * @param bgActivityId  the value for user_bg_info.bg_activity_id
	 * @mbggenerated
	 */
	public void setBgActivityId(Integer bgActivityId) {
		this.bgActivityId = bgActivityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_bg_info.is_state
	 * @return  the value of user_bg_info.is_state
	 * @mbggenerated
	 */
	public String getIsState() {
		return isState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_bg_info.is_state
	 * @param isState  the value for user_bg_info.is_state
	 * @mbggenerated
	 */
	public void setIsState(String isState) {
		this.isState = isState == null ? null : isState.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_bg_info.rs
	 * @return  the value of user_bg_info.rs
	 * @mbggenerated
	 */
	public String getRs() {
		return rs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_bg_info.rs
	 * @param rs  the value for user_bg_info.rs
	 * @mbggenerated
	 */
	public void setRs(String rs) {
		this.rs = rs == null ? null : rs.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_bg_info.up_state
	 * @return  the value of user_bg_info.up_state
	 * @mbggenerated
	 */
	public String getUpState() {
		return upState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_bg_info.up_state
	 * @param upState  the value for user_bg_info.up_state
	 * @mbggenerated
	 */
	public void setUpState(String upState) {
		this.upState = upState == null ? null : upState.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_bg_info.class_id
	 * @return  the value of user_bg_info.class_id
	 * @mbggenerated
	 */
	public Integer getClassId() {
		return classId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_bg_info.class_id
	 * @param classId  the value for user_bg_info.class_id
	 * @mbggenerated
	 */
	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_bg_info.del_date
	 * @return  the value of user_bg_info.del_date
	 * @mbggenerated
	 */
	public Date getDelDate() {
		return delDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_bg_info.del_date
	 * @param delDate  the value for user_bg_info.del_date
	 * @mbggenerated
	 */
	public void setDelDate(Date delDate) {
		this.delDate = delDate;
	}
}