package com.i84.earnpoint.model;

import java.util.Date;

public class ZcActivityInfo extends Page implements java.io.Serializable{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zc_activity_info.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zc_activity_info.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zc_activity_info.business_id
	 * @mbggenerated
	 */
	private Integer businessId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zc_activity_info.s_startdate
	 * @mbggenerated
	 */
	private Date sStartdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zc_activity_info.s_enddate
	 * @mbggenerated
	 */
	private Date sEnddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zc_activity_info.p_startdate
	 * @mbggenerated
	 */
	private Date pStartdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zc_activity_info.p_enddate
	 * @mbggenerated
	 */
	private Date pEnddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zc_activity_info.h_enddate
	 * @mbggenerated
	 */
	private Date hEnddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zc_activity_info.remark
	 * @mbggenerated
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zc_activity_info.state
	 * @mbggenerated
	 */
	private String state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zc_activity_info.del_date
	 * @mbggenerated
	 */
	private Date delDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zc_activity_info.z_name
	 * @mbggenerated
	 */
	private String zName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zc_activity_info.z_url
	 * @mbggenerated
	 */
	private String zUrl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zc_activity_info.id
	 * @return  the value of zc_activity_info.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zc_activity_info.id
	 * @param id  the value for zc_activity_info.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zc_activity_info.name
	 * @return  the value of zc_activity_info.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zc_activity_info.name
	 * @param name  the value for zc_activity_info.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zc_activity_info.business_id
	 * @return  the value of zc_activity_info.business_id
	 * @mbggenerated
	 */
	public Integer getBusinessId() {
		return businessId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zc_activity_info.business_id
	 * @param businessId  the value for zc_activity_info.business_id
	 * @mbggenerated
	 */
	public void setBusinessId(Integer businessId) {
		this.businessId = businessId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zc_activity_info.s_startdate
	 * @return  the value of zc_activity_info.s_startdate
	 * @mbggenerated
	 */
	public Date getsStartdate() {
		return sStartdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zc_activity_info.s_startdate
	 * @param sStartdate  the value for zc_activity_info.s_startdate
	 * @mbggenerated
	 */
	public void setsStartdate(Date sStartdate) {
		this.sStartdate = sStartdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zc_activity_info.s_enddate
	 * @return  the value of zc_activity_info.s_enddate
	 * @mbggenerated
	 */
	public Date getsEnddate() {
		return sEnddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zc_activity_info.s_enddate
	 * @param sEnddate  the value for zc_activity_info.s_enddate
	 * @mbggenerated
	 */
	public void setsEnddate(Date sEnddate) {
		this.sEnddate = sEnddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zc_activity_info.p_startdate
	 * @return  the value of zc_activity_info.p_startdate
	 * @mbggenerated
	 */
	public Date getpStartdate() {
		return pStartdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zc_activity_info.p_startdate
	 * @param pStartdate  the value for zc_activity_info.p_startdate
	 * @mbggenerated
	 */
	public void setpStartdate(Date pStartdate) {
		this.pStartdate = pStartdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zc_activity_info.p_enddate
	 * @return  the value of zc_activity_info.p_enddate
	 * @mbggenerated
	 */
	public Date getpEnddate() {
		return pEnddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zc_activity_info.p_enddate
	 * @param pEnddate  the value for zc_activity_info.p_enddate
	 * @mbggenerated
	 */
	public void setpEnddate(Date pEnddate) {
		this.pEnddate = pEnddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zc_activity_info.h_enddate
	 * @return  the value of zc_activity_info.h_enddate
	 * @mbggenerated
	 */
	public Date gethEnddate() {
		return hEnddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zc_activity_info.h_enddate
	 * @param hEnddate  the value for zc_activity_info.h_enddate
	 * @mbggenerated
	 */
	public void sethEnddate(Date hEnddate) {
		this.hEnddate = hEnddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zc_activity_info.remark
	 * @return  the value of zc_activity_info.remark
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zc_activity_info.remark
	 * @param remark  the value for zc_activity_info.remark
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zc_activity_info.state
	 * @return  the value of zc_activity_info.state
	 * @mbggenerated
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zc_activity_info.state
	 * @param state  the value for zc_activity_info.state
	 * @mbggenerated
	 */
	public void setState(String state) {
		this.state = state == null ? null : state.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zc_activity_info.del_date
	 * @return  the value of zc_activity_info.del_date
	 * @mbggenerated
	 */
	public Date getDelDate() {
		return delDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zc_activity_info.del_date
	 * @param delDate  the value for zc_activity_info.del_date
	 * @mbggenerated
	 */
	public void setDelDate(Date delDate) {
		this.delDate = delDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zc_activity_info.z_name
	 * @return  the value of zc_activity_info.z_name
	 * @mbggenerated
	 */
	public String getzName() {
		return zName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zc_activity_info.z_name
	 * @param zName  the value for zc_activity_info.z_name
	 * @mbggenerated
	 */
	public void setzName(String zName) {
		this.zName = zName == null ? null : zName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zc_activity_info.z_url
	 * @return  the value of zc_activity_info.z_url
	 * @mbggenerated
	 */
	public String getzUrl() {
		return zUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zc_activity_info.z_url
	 * @param zUrl  the value for zc_activity_info.z_url
	 * @mbggenerated
	 */
	public void setzUrl(String zUrl) {
		this.zUrl = zUrl;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
}