package com.i84.earnpoint.model;

import java.util.Date;

public class UserExpertInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_expert_info.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_expert_info.uid
	 * @mbggenerated
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_expert_info.company
	 * @mbggenerated
	 */
	private String company;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_expert_info.zpno
	 * @mbggenerated
	 */
	private String zpno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_expert_info.pro_type
	 * @mbggenerated
	 */
	private String proType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_expert_info.zg_level
	 * @mbggenerated
	 */
	private String zgLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_expert_info.staff
	 * @mbggenerated
	 */
	private Integer staff;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_expert_info.add_date
	 * @mbggenerated
	 */
	private Date addDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_expert_info.del_date
	 * @mbggenerated
	 */
	private Date delDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_expert_info.login_times
	 * @mbggenerated
	 */
	private Integer loginTimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_expert_info.init_time
	 * @mbggenerated
	 */
	private Integer initTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_expert_info.other_time
	 * @mbggenerated
	 */
	private Integer otherTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_expert_info.login_date
	 * @mbggenerated
	 */
	private Date loginDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_expert_info.id
	 * @return  the value of user_expert_info.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_expert_info.id
	 * @param id  the value for user_expert_info.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_expert_info.uid
	 * @return  the value of user_expert_info.uid
	 * @mbggenerated
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_expert_info.uid
	 * @param uid  the value for user_expert_info.uid
	 * @mbggenerated
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_expert_info.company
	 * @return  the value of user_expert_info.company
	 * @mbggenerated
	 */
	public String getCompany() {
		return company;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_expert_info.company
	 * @param company  the value for user_expert_info.company
	 * @mbggenerated
	 */
	public void setCompany(String company) {
		this.company = company == null ? null : company.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_expert_info.zpno
	 * @return  the value of user_expert_info.zpno
	 * @mbggenerated
	 */
	public String getZpno() {
		return zpno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_expert_info.zpno
	 * @param zpno  the value for user_expert_info.zpno
	 * @mbggenerated
	 */
	public void setZpno(String zpno) {
		this.zpno = zpno == null ? null : zpno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_expert_info.pro_type
	 * @return  the value of user_expert_info.pro_type
	 * @mbggenerated
	 */
	public String getProType() {
		return proType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_expert_info.pro_type
	 * @param proType  the value for user_expert_info.pro_type
	 * @mbggenerated
	 */
	public void setProType(String proType) {
		this.proType = proType == null ? null : proType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_expert_info.zg_level
	 * @return  the value of user_expert_info.zg_level
	 * @mbggenerated
	 */
	public String getZgLevel() {
		return zgLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_expert_info.zg_level
	 * @param zgLevel  the value for user_expert_info.zg_level
	 * @mbggenerated
	 */
	public void setZgLevel(String zgLevel) {
		this.zgLevel = zgLevel == null ? null : zgLevel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_expert_info.staff
	 * @return  the value of user_expert_info.staff
	 * @mbggenerated
	 */
	public Integer getStaff() {
		return staff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_expert_info.staff
	 * @param staff  the value for user_expert_info.staff
	 * @mbggenerated
	 */
	public void setStaff(Integer staff) {
		this.staff = staff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_expert_info.add_date
	 * @return  the value of user_expert_info.add_date
	 * @mbggenerated
	 */
	public Date getAddDate() {
		return addDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_expert_info.add_date
	 * @param addDate  the value for user_expert_info.add_date
	 * @mbggenerated
	 */
	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_expert_info.del_date
	 * @return  the value of user_expert_info.del_date
	 * @mbggenerated
	 */
	public Date getDelDate() {
		return delDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_expert_info.del_date
	 * @param delDate  the value for user_expert_info.del_date
	 * @mbggenerated
	 */
	public void setDelDate(Date delDate) {
		this.delDate = delDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_expert_info.login_times
	 * @return  the value of user_expert_info.login_times
	 * @mbggenerated
	 */
	public Integer getLoginTimes() {
		return loginTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_expert_info.login_times
	 * @param loginTimes  the value for user_expert_info.login_times
	 * @mbggenerated
	 */
	public void setLoginTimes(Integer loginTimes) {
		this.loginTimes = loginTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_expert_info.init_time
	 * @return  the value of user_expert_info.init_time
	 * @mbggenerated
	 */
	public Integer getInitTime() {
		return initTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_expert_info.init_time
	 * @param initTime  the value for user_expert_info.init_time
	 * @mbggenerated
	 */
	public void setInitTime(Integer initTime) {
		this.initTime = initTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_expert_info.other_time
	 * @return  the value of user_expert_info.other_time
	 * @mbggenerated
	 */
	public Integer getOtherTime() {
		return otherTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_expert_info.other_time
	 * @param otherTime  the value for user_expert_info.other_time
	 * @mbggenerated
	 */
	public void setOtherTime(Integer otherTime) {
		this.otherTime = otherTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_expert_info.login_date
	 * @return  the value of user_expert_info.login_date
	 * @mbggenerated
	 */
	public Date getLoginDate() {
		return loginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_expert_info.login_date
	 * @param loginDate  the value for user_expert_info.login_date
	 * @mbggenerated
	 */
	public void setLoginDate(Date loginDate) {
		this.loginDate = loginDate;
	}
}