package com.i84.earnpoint.model;

import java.io.Serializable;
import java.util.Date;

import com.i84.earnpoint.common.SystemContant;
/**
 * 享受国务院特殊津贴
 * @author Administrator
 *
 */
public class PersonStateAllowance extends Page implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_state_allowance.id
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_state_allowance.givenDate
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private String givendate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_state_allowance.number
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private String number;
    /**
     * 身份证号码
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_state_allowance.pid
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private Integer pid;
    private Date createDate;
    /**
     * 删除状态
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_state_allowance.del_status
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    private String delStatus = SystemContant.STATUS_USABLE;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_state_allowance.id
     *
     * @return the value of person_state_allowance.id
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_state_allowance.id
     *
     * @param id the value for person_state_allowance.id
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_state_allowance.givenDate
     *
     * @return the value of person_state_allowance.givenDate
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public String getGivendate() {
        return givendate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_state_allowance.givenDate
     *
     * @param givendate the value for person_state_allowance.givenDate
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public void setGivendate(String givendate) {
        this.givendate = givendate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_state_allowance.number
     *
     * @return the value of person_state_allowance.number
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_state_allowance.number
     *
     * @param number the value for person_state_allowance.number
     *
     * @mbggenerated Tue Sep 20 23:04:10 CST 2016
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

	public Integer getPid() {
		return pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getDelStatus() {
		return delStatus;
	}

	public void setDelStatus(String delStatus) {
		this.delStatus = delStatus;
	}
    
}