package com.i84.earnpoint.mapper;

import java.util.List;
import java.util.Map;

import com.i84.earnpoint.gdcl.BO.SerchBO;
import com.i84.earnpoint.model.ArchivesMaterialInfo;

public interface ArchivesMaterialInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archives_material_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archives_material_info
     *
     * @mbggenerated
     */
    int insert(ArchivesMaterialInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archives_material_info
     *
     * @mbggenerated
     */
    int insertSelective(ArchivesMaterialInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archives_material_info
     *
     * @mbggenerated
     */
    ArchivesMaterialInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archives_material_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ArchivesMaterialInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archives_material_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ArchivesMaterialInfo record);
    
    List<Map<String,Object>> selectByPno(ArchivesMaterialInfo record);
    /**
     * 查询材料清单
     * @param pno
     * @return
     */
    List<Map<String,Object>> selectAllGdMaterialsByPno(String pno);
    
    int sort(SerchBO serchBO);
    int delete_cl(Map<String,Object> map);
    
    Map<String,Object> getsort(Map<String,Object> map);
}