package com.i84.earnpoint.model;

import java.util.Date;

public class ExamResultInfo extends Page{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_result_info.result_id
     *
     * @mbggenerated Tue Sep 27 22:45:06 CST 2016
     */
    private Integer resultId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_result_info.class_name
     *
     * @mbggenerated Tue Sep 27 22:45:06 CST 2016
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_result_info.class_num
     *
     * @mbggenerated Tue Sep 27 22:45:06 CST 2016
     */
    private String classNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_result_info.card_id
     *
     * @mbggenerated Tue Sep 27 22:45:06 CST 2016
     */
    private String cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_result_info.user_name
     *
     * @mbggenerated Tue Sep 27 22:45:06 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_result_info.result_score
     *
     * @mbggenerated Tue Sep 27 22:45:06 CST 2016
     */
    private String resultScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_result_info.create_time
     *
     * @mbggenerated Tue Sep 27 22:45:06 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_result_info.status
     *
     * @mbggenerated Tue Sep 27 22:45:06 CST 2016
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_result_info.result_id
     *
     * @return the value of exam_result_info.result_id
     *
     * @mbggenerated Tue Sep 27 22:45:06 CST 2016
     */
    public Integer getResultId() {
        return resultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_result_info.result_id
     *
     * @param resultId the value for exam_result_info.result_id
     *
     * @mbggenerated Tue Sep 27 22:45:06 CST 2016
     */
    public void setResultId(Integer resultId) {
        this.resultId = resultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_result_info.class_name
     *
     * @return the value of exam_result_info.class_name
     *
     * @mbggenerated Tue Sep 27 22:45:06 CST 2016
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_result_info.class_name
     *
     * @param className the value for exam_result_info.class_name
     *
     * @mbggenerated Tue Sep 27 22:45:06 CST 2016
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_result_info.class_num
     *
     * @return the value of exam_result_info.class_num
     *
     * @mbggenerated Tue Sep 27 22:45:06 CST 2016
     */
    public String getClassNum() {
        return classNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_result_info.class_num
     *
     * @param classNum the value for exam_result_info.class_num
     *
     * @mbggenerated Tue Sep 27 22:45:06 CST 2016
     */
    public void setClassNum(String classNum) {
        this.classNum = classNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_result_info.card_id
     *
     * @return the value of exam_result_info.card_id
     *
     * @mbggenerated Tue Sep 27 22:45:06 CST 2016
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_result_info.card_id
     *
     * @param cardId the value for exam_result_info.card_id
     *
     * @mbggenerated Tue Sep 27 22:45:06 CST 2016
     */
    public void setCardId(String cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_result_info.user_name
     *
     * @return the value of exam_result_info.user_name
     *
     * @mbggenerated Tue Sep 27 22:45:06 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_result_info.user_name
     *
     * @param userName the value for exam_result_info.user_name
     *
     * @mbggenerated Tue Sep 27 22:45:06 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_result_info.result_score
     *
     * @return the value of exam_result_info.result_score
     *
     * @mbggenerated Tue Sep 27 22:45:06 CST 2016
     */
    public String getResultScore() {
        return resultScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_result_info.result_score
     *
     * @param resultScore the value for exam_result_info.result_score
     *
     * @mbggenerated Tue Sep 27 22:45:06 CST 2016
     */
    public void setResultScore(String resultScore) {
        this.resultScore = resultScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_result_info.create_time
     *
     * @return the value of exam_result_info.create_time
     *
     * @mbggenerated Tue Sep 27 22:45:06 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_result_info.create_time
     *
     * @param createTime the value for exam_result_info.create_time
     *
     * @mbggenerated Tue Sep 27 22:45:06 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_result_info.status
     *
     * @return the value of exam_result_info.status
     *
     * @mbggenerated Tue Sep 27 22:45:06 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_result_info.status
     *
     * @param status the value for exam_result_info.status
     *
     * @mbggenerated Tue Sep 27 22:45:06 CST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }
    
}