package com.i84.earnpoint.mapper;

import com.i84.earnpoint.model.AqscMsgInfo;

public interface AqscMsgInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aqsc_msg_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aqsc_msg_info
     *
     * @mbggenerated
     */
    int insert(AqscMsgInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aqsc_msg_info
     *
     * @mbggenerated
     */
    int insertSelective(AqscMsgInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aqsc_msg_info
     *
     * @mbggenerated
     */
    AqscMsgInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aqsc_msg_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AqscMsgInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aqsc_msg_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AqscMsgInfo record);
}