package com.i84.earnpoint.model;

import java.util.Date;

public class ArchivesMoneyInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column archives_money_info.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column archives_money_info.ar_no
	 * @mbggenerated
	 */
	private String arNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column archives_money_info.proxy_name
	 * @mbggenerated
	 */
	private String proxyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column archives_money_info.jf_type
	 * @mbggenerated
	 */
	private String jfType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column archives_money_info.jf_date
	 * @mbggenerated
	 */
	private String jfDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column archives_money_info.p_no
	 * @mbggenerated
	 */
	private String pNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column archives_money_info.s_date
	 * @mbggenerated
	 */
	private String sDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column archives_money_info.e_date
	 * @mbggenerated
	 */
	private String eDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column archives_money_info.m
	 * @mbggenerated
	 */
	private Float m;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column archives_money_info.jf_name
	 * @mbggenerated
	 */
	private String jfName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column archives_money_info.del_date
	 * @mbggenerated
	 */
	private String delDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column archives_money_info.id
	 * @return  the value of archives_money_info.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column archives_money_info.id
	 * @param id  the value for archives_money_info.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column archives_money_info.ar_no
	 * @return  the value of archives_money_info.ar_no
	 * @mbggenerated
	 */
	public String getArNo() {
		return arNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column archives_money_info.ar_no
	 * @param arNo  the value for archives_money_info.ar_no
	 * @mbggenerated
	 */
	public void setArNo(String arNo) {
		this.arNo = arNo == null ? null : arNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column archives_money_info.proxy_name
	 * @return  the value of archives_money_info.proxy_name
	 * @mbggenerated
	 */
	public String getProxyName() {
		return proxyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column archives_money_info.proxy_name
	 * @param proxyName  the value for archives_money_info.proxy_name
	 * @mbggenerated
	 */
	public void setProxyName(String proxyName) {
		this.proxyName = proxyName == null ? null : proxyName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column archives_money_info.jf_type
	 * @return  the value of archives_money_info.jf_type
	 * @mbggenerated
	 */
	public String getJfType() {
		return jfType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column archives_money_info.jf_type
	 * @param jfType  the value for archives_money_info.jf_type
	 * @mbggenerated
	 */
	public void setJfType(String jfType) {
		this.jfType = jfType == null ? null : jfType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column archives_money_info.jf_date
	 * @return  the value of archives_money_info.jf_date
	 * @mbggenerated
	 */
	public String getJfDate() {
		return jfDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column archives_money_info.jf_date
	 * @param jfDate  the value for archives_money_info.jf_date
	 * @mbggenerated
	 */
	public void setJfDate(String jfDate) {
		this.jfDate = jfDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column archives_money_info.p_no
	 * @return  the value of archives_money_info.p_no
	 * @mbggenerated
	 */
	public String getpNo() {
		return pNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column archives_money_info.p_no
	 * @param pNo  the value for archives_money_info.p_no
	 * @mbggenerated
	 */
	public void setpNo(String pNo) {
		this.pNo = pNo == null ? null : pNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column archives_money_info.s_date
	 * @return  the value of archives_money_info.s_date
	 * @mbggenerated
	 */
	public String getsDate() {
		return sDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column archives_money_info.s_date
	 * @param sDate  the value for archives_money_info.s_date
	 * @mbggenerated
	 */
	public void setsDate(String sDate) {
		this.sDate = sDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column archives_money_info.e_date
	 * @return  the value of archives_money_info.e_date
	 * @mbggenerated
	 */
	public String geteDate() {
		return eDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column archives_money_info.e_date
	 * @param eDate  the value for archives_money_info.e_date
	 * @mbggenerated
	 */
	public void seteDate(String eDate) {
		this.eDate = eDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column archives_money_info.m
	 * @return  the value of archives_money_info.m
	 * @mbggenerated
	 */
	public Float getM() {
		return m;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column archives_money_info.m
	 * @param m  the value for archives_money_info.m
	 * @mbggenerated
	 */
	public void setM(Float m) {
		this.m = m;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column archives_money_info.jf_name
	 * @return  the value of archives_money_info.jf_name
	 * @mbggenerated
	 */
	public String getJfName() {
		return jfName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column archives_money_info.jf_name
	 * @param jfName  the value for archives_money_info.jf_name
	 * @mbggenerated
	 */
	public void setJfName(String jfName) {
		this.jfName = jfName == null ? null : jfName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column archives_money_info.del_date
	 * @return  the value of archives_money_info.del_date
	 * @mbggenerated
	 */
	public String getDelDate() {
		return delDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column archives_money_info.del_date
	 * @param delDate  the value for archives_money_info.del_date
	 * @mbggenerated
	 */
	public void setDelDate(String delDate) {
		this.delDate = delDate;
	}
}