package com.i84.earnpoint.model;

import java.util.Date;

public class HyBusinessInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hy_business_info.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hy_business_info.user_id
	 * @mbggenerated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hy_business_info.employment_type_id
	 * @mbggenerated
	 */
	private String employmentTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hy_business_info.remsg
	 * @mbggenerated
	 */
	private String remsg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hy_business_info.enterprise_id
	 * @mbggenerated
	 */
	private Integer enterpriseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hy_business_info.sstate
	 * @mbggenerated
	 */
	private Integer sstate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hy_business_info.uid
	 * @mbggenerated
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hy_business_info.add_date
	 * @mbggenerated
	 */
	private Date addDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hy_business_info.del_date
	 * @mbggenerated
	 */
	private Date delDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hy_business_info.id
	 * @return  the value of hy_business_info.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hy_business_info.id
	 * @param id  the value for hy_business_info.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hy_business_info.user_id
	 * @return  the value of hy_business_info.user_id
	 * @mbggenerated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hy_business_info.user_id
	 * @param userId  the value for hy_business_info.user_id
	 * @mbggenerated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hy_business_info.employment_type_id
	 * @return  the value of hy_business_info.employment_type_id
	 * @mbggenerated
	 */
	public String getEmploymentTypeId() {
		return employmentTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hy_business_info.employment_type_id
	 * @param employmentTypeId  the value for hy_business_info.employment_type_id
	 * @mbggenerated
	 */
	public void setEmploymentTypeId(String employmentTypeId) {
		this.employmentTypeId = employmentTypeId == null ? null
				: employmentTypeId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hy_business_info.remsg
	 * @return  the value of hy_business_info.remsg
	 * @mbggenerated
	 */
	public String getRemsg() {
		return remsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hy_business_info.remsg
	 * @param remsg  the value for hy_business_info.remsg
	 * @mbggenerated
	 */
	public void setRemsg(String remsg) {
		this.remsg = remsg == null ? null : remsg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hy_business_info.enterprise_id
	 * @return  the value of hy_business_info.enterprise_id
	 * @mbggenerated
	 */
	public Integer getEnterpriseId() {
		return enterpriseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hy_business_info.enterprise_id
	 * @param enterpriseId  the value for hy_business_info.enterprise_id
	 * @mbggenerated
	 */
	public void setEnterpriseId(Integer enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hy_business_info.sstate
	 * @return  the value of hy_business_info.sstate
	 * @mbggenerated
	 */
	public Integer getSstate() {
		return sstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hy_business_info.sstate
	 * @param sstate  the value for hy_business_info.sstate
	 * @mbggenerated
	 */
	public void setSstate(Integer sstate) {
		this.sstate = sstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hy_business_info.uid
	 * @return  the value of hy_business_info.uid
	 * @mbggenerated
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hy_business_info.uid
	 * @param uid  the value for hy_business_info.uid
	 * @mbggenerated
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hy_business_info.add_date
	 * @return  the value of hy_business_info.add_date
	 * @mbggenerated
	 */
	public Date getAddDate() {
		return addDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hy_business_info.add_date
	 * @param addDate  the value for hy_business_info.add_date
	 * @mbggenerated
	 */
	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hy_business_info.del_date
	 * @return  the value of hy_business_info.del_date
	 * @mbggenerated
	 */
	public Date getDelDate() {
		return delDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hy_business_info.del_date
	 * @param delDate  the value for hy_business_info.del_date
	 * @mbggenerated
	 */
	public void setDelDate(Date delDate) {
		this.delDate = delDate;
	}
}