package com.i84.earnpoint.model;

public class BgEnterprisePlaceInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_enterprise_place_info.id
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_enterprise_place_info.activity_enterprise_id
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    private Integer activityEnterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_enterprise_place_info.place_id
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    private Integer placeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_enterprise_place_info.recruitment_num
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    private Integer recruitmentNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_enterprise_place_info.age_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    private String ageRange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_enterprise_place_info.gender_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    private String genderRange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_enterprise_place_info.nation_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    private String nationRange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_enterprise_place_info.political_status_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    private String politicalStatusRange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_enterprise_place_info.education_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    private String educationRange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_enterprise_place_info.school_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    private String schoolRange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_enterprise_place_info.education_type_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    private String educationTypeRange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_enterprise_place_info.profession_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    private String professionRange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_enterprise_place_info.paper_style
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    private String paperStyle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_enterprise_place_info.examination_name
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    private String examinationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_enterprise_place_info.examination_place
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    private String examinationPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_enterprise_place_info.examination_subject
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    private String examinationSubject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_enterprise_place_info.is_start
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    private String isStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_enterprise_place_info.others_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    private String othersRange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bg_enterprise_place_info.remark
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_enterprise_place_info.id
     *
     * @return the value of bg_enterprise_place_info.id
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_enterprise_place_info.id
     *
     * @param id the value for bg_enterprise_place_info.id
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_enterprise_place_info.activity_enterprise_id
     *
     * @return the value of bg_enterprise_place_info.activity_enterprise_id
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public Integer getActivityEnterpriseId() {
        return activityEnterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_enterprise_place_info.activity_enterprise_id
     *
     * @param activityEnterpriseId the value for bg_enterprise_place_info.activity_enterprise_id
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public void setActivityEnterpriseId(Integer activityEnterpriseId) {
        this.activityEnterpriseId = activityEnterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_enterprise_place_info.place_id
     *
     * @return the value of bg_enterprise_place_info.place_id
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public Integer getPlaceId() {
        return placeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_enterprise_place_info.place_id
     *
     * @param placeId the value for bg_enterprise_place_info.place_id
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public void setPlaceId(Integer placeId) {
        this.placeId = placeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_enterprise_place_info.recruitment_num
     *
     * @return the value of bg_enterprise_place_info.recruitment_num
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public Integer getRecruitmentNum() {
        return recruitmentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_enterprise_place_info.recruitment_num
     *
     * @param recruitmentNum the value for bg_enterprise_place_info.recruitment_num
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public void setRecruitmentNum(Integer recruitmentNum) {
        this.recruitmentNum = recruitmentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_enterprise_place_info.age_range
     *
     * @return the value of bg_enterprise_place_info.age_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public String getAgeRange() {
        return ageRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_enterprise_place_info.age_range
     *
     * @param ageRange the value for bg_enterprise_place_info.age_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public void setAgeRange(String ageRange) {
        this.ageRange = ageRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_enterprise_place_info.gender_range
     *
     * @return the value of bg_enterprise_place_info.gender_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public String getGenderRange() {
        return genderRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_enterprise_place_info.gender_range
     *
     * @param genderRange the value for bg_enterprise_place_info.gender_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public void setGenderRange(String genderRange) {
        this.genderRange = genderRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_enterprise_place_info.nation_range
     *
     * @return the value of bg_enterprise_place_info.nation_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public String getNationRange() {
        return nationRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_enterprise_place_info.nation_range
     *
     * @param nationRange the value for bg_enterprise_place_info.nation_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public void setNationRange(String nationRange) {
        this.nationRange = nationRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_enterprise_place_info.political_status_range
     *
     * @return the value of bg_enterprise_place_info.political_status_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public String getPoliticalStatusRange() {
        return politicalStatusRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_enterprise_place_info.political_status_range
     *
     * @param politicalStatusRange the value for bg_enterprise_place_info.political_status_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public void setPoliticalStatusRange(String politicalStatusRange) {
        this.politicalStatusRange = politicalStatusRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_enterprise_place_info.education_range
     *
     * @return the value of bg_enterprise_place_info.education_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public String getEducationRange() {
        return educationRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_enterprise_place_info.education_range
     *
     * @param educationRange the value for bg_enterprise_place_info.education_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public void setEducationRange(String educationRange) {
        this.educationRange = educationRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_enterprise_place_info.school_range
     *
     * @return the value of bg_enterprise_place_info.school_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public String getSchoolRange() {
        return schoolRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_enterprise_place_info.school_range
     *
     * @param schoolRange the value for bg_enterprise_place_info.school_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public void setSchoolRange(String schoolRange) {
        this.schoolRange = schoolRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_enterprise_place_info.education_type_range
     *
     * @return the value of bg_enterprise_place_info.education_type_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public String getEducationTypeRange() {
        return educationTypeRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_enterprise_place_info.education_type_range
     *
     * @param educationTypeRange the value for bg_enterprise_place_info.education_type_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public void setEducationTypeRange(String educationTypeRange) {
        this.educationTypeRange = educationTypeRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_enterprise_place_info.profession_range
     *
     * @return the value of bg_enterprise_place_info.profession_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public String getProfessionRange() {
        return professionRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_enterprise_place_info.profession_range
     *
     * @param professionRange the value for bg_enterprise_place_info.profession_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public void setProfessionRange(String professionRange) {
        this.professionRange = professionRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_enterprise_place_info.paper_style
     *
     * @return the value of bg_enterprise_place_info.paper_style
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public String getPaperStyle() {
        return paperStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_enterprise_place_info.paper_style
     *
     * @param paperStyle the value for bg_enterprise_place_info.paper_style
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public void setPaperStyle(String paperStyle) {
        this.paperStyle = paperStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_enterprise_place_info.examination_name
     *
     * @return the value of bg_enterprise_place_info.examination_name
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public String getExaminationName() {
        return examinationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_enterprise_place_info.examination_name
     *
     * @param examinationName the value for bg_enterprise_place_info.examination_name
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public void setExaminationName(String examinationName) {
        this.examinationName = examinationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_enterprise_place_info.examination_place
     *
     * @return the value of bg_enterprise_place_info.examination_place
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public String getExaminationPlace() {
        return examinationPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_enterprise_place_info.examination_place
     *
     * @param examinationPlace the value for bg_enterprise_place_info.examination_place
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public void setExaminationPlace(String examinationPlace) {
        this.examinationPlace = examinationPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_enterprise_place_info.examination_subject
     *
     * @return the value of bg_enterprise_place_info.examination_subject
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public String getExaminationSubject() {
        return examinationSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_enterprise_place_info.examination_subject
     *
     * @param examinationSubject the value for bg_enterprise_place_info.examination_subject
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public void setExaminationSubject(String examinationSubject) {
        this.examinationSubject = examinationSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_enterprise_place_info.is_start
     *
     * @return the value of bg_enterprise_place_info.is_start
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public String getIsStart() {
        return isStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_enterprise_place_info.is_start
     *
     * @param isStart the value for bg_enterprise_place_info.is_start
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public void setIsStart(String isStart) {
        this.isStart = isStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_enterprise_place_info.others_range
     *
     * @return the value of bg_enterprise_place_info.others_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public String getOthersRange() {
        return othersRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_enterprise_place_info.others_range
     *
     * @param othersRange the value for bg_enterprise_place_info.others_range
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public void setOthersRange(String othersRange) {
        this.othersRange = othersRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bg_enterprise_place_info.remark
     *
     * @return the value of bg_enterprise_place_info.remark
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bg_enterprise_place_info.remark
     *
     * @param remark the value for bg_enterprise_place_info.remark
     *
     * @mbg.generated Wed Sep 07 23:57:10 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}