package com.i84.earnpoint.mapper;

import java.util.List;
import java.util.Map;

import com.i84.earnpoint.model.UserMaterialInfo;

public interface UserMaterialInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_material_info
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_material_info
	 * @mbggenerated
	 */
	int insert(UserMaterialInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_material_info
	 * @mbggenerated
	 */
	int insertSelective(UserMaterialInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_material_info
	 * @mbggenerated
	 */
	UserMaterialInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_material_info
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(UserMaterialInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_material_info
	 * @mbggenerated
	 */
	int updateByPrimaryKey(UserMaterialInfo record);
	
	List<UserMaterialInfo> selectBySelective(UserMaterialInfo userMaterialInfo);
	
	int updateIsValid(String []array);
	
	
}