package com.i84.earnpoint.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.i84.earnpoint.model.BgActivityUserInfo;
import com.i84.earnpoint.model.BgActivityUserInfoExample;
import com.i84.earnpoint.model.ExportScore;

public interface BgActivityUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_info
     *
     * @mbg.generated Mon Sep 12 09:45:19 CST 2016
     */
    long countByExample(BgActivityUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_info
     *
     * @mbg.generated Mon Sep 12 09:45:19 CST 2016
     */
    int deleteByExample(BgActivityUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_info
     *
     * @mbg.generated Mon Sep 12 09:45:19 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_info
     *
     * @mbg.generated Mon Sep 12 09:45:19 CST 2016
     */
    int insert(BgActivityUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_info
     *
     * @mbg.generated Mon Sep 12 09:45:19 CST 2016
     */
    int insertSelective(BgActivityUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_info
     *
     * @mbg.generated Mon Sep 12 09:45:19 CST 2016
     */
    List<BgActivityUserInfo> selectByExample(BgActivityUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_info
     *
     * @mbg.generated Mon Sep 12 09:45:19 CST 2016
     */
    BgActivityUserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_info
     *
     * @mbg.generated Mon Sep 12 09:45:19 CST 2016
     */
    int updateByExampleSelective(@Param("record") BgActivityUserInfo record, @Param("example") BgActivityUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_info
     *
     * @mbg.generated Mon Sep 12 09:45:19 CST 2016
     */
    int updateByExample(@Param("record") BgActivityUserInfo record, @Param("example") BgActivityUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_info
     *
     * @mbg.generated Mon Sep 12 09:45:19 CST 2016
     */
    int updateByPrimaryKeySelective(BgActivityUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bg_activity_user_info
     *
     * @mbg.generated Mon Sep 12 09:45:19 CST 2016
     */
    int updateByPrimaryKey(BgActivityUserInfo record);

    List<Map<String,Object>> selectListBySelective(Map<String,Object> record);

    List<Map<String,Object>> queryEnterpriseInfo(Map<String,Object> record);
    List<Map<String,Object>> queryUserInfo(Map<String,Object> record);
    List<Map<String,Object>> queryUserStudyInfo(Map<String,Object> record);
    List<Map<String,Object>> queryUserWorkInfo(Map<String,Object> record);
    List<Map<String,Object>> queryGwyqInfo(Map<String,Object> record);

    List<Map<String,Object>> queryShFailedList(Map<String,Object> record);
    List<Map<String,Object>> queryShFailedList2(Map<String,Object> record);

    List<Map<String,Object>> activityList(String date);

    List<Map<String,Object>> userList(Map<String,Object> record);
    List<Map<String,Object>> userListByzkz(Map<String,Object> record);
    List<Map<String,Object>> kshList(Map<String,Object> record);

    List<Map<String,Object>> queryShSsInfo(Map<String,Object> record);
    List<Map<String,Object>> activityAllUserList(Map<String,Object> record);
    List<Map<String,Object>> userEnterprises(Map<String,Object> record);
    List<Map<String,Object>> userEnterpriseId(int userId);
    List<Map<String,Object>> userEnterpriseIds(int id);

    List<Map<String, Object>> userEnterpriseAll();

    List<Map<String, Object>> activityenterpriseList(Map<String, Object> params);

    List<Map<String, Object>> activityenterpriseplaceList(Integer id);
    int updateInfo(BgActivityUserInfo record);
}